package com.ctg.dms.common;


public enum JobDetailsFields{
	STATUS,
	KILLED,
	RETRIES, 
	RERAN, 
	PROCESS_STARTED_ON, 
	TRANSFORM_STARTED_ON, 
	TRANSFORM_STOPPED_ON, 
	PROCESS_STOPPED_ON,  
	JOB_URL,
	JOB_PROCESSOR_NAME,
	HEART_BEAT,
	SRQ_FULLFILMENT_TEXT,
	NO_DATA_FOUND,
	FAILURE_NOTIFIED,
	FAILURE_MESSAGE
}
