//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.14 at 10:55:58 AM BST 
//


package org.etsi.uri._02657.v1_7_1_.retaineddata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

import org.etsi.uri._02657.v1_1_1_.retaineddata.NULL;


/**
 * <p>Java class for MultimediaCommunicationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MultimediaCommunicationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="multimediaFixed" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *         &lt;element name="multimediaWireless" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *         &lt;element name="multimediaNetworkIndependent" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MultimediaCommunicationType", propOrder = {
    "multimediaFixed",
    "multimediaWireless",
    "multimediaNetworkIndependent"
})
public class MultimediaCommunicationType {

    protected NULL multimediaFixed;
    protected NULL multimediaWireless;
    protected NULL multimediaNetworkIndependent;

    /**
     * Gets the value of the multimediaFixed property.
     * 
     * @return
     *     possible object is
     *     {@link NULL }
     *     
     */
    public NULL getMultimediaFixed() {
        return multimediaFixed;
    }

    /**
     * Sets the value of the multimediaFixed property.
     * 
     * @param value
     *     allowed object is
     *     {@link NULL }
     *     
     */
    public void setMultimediaFixed(NULL value) {
        this.multimediaFixed = value;
    }

    /**
     * Gets the value of the multimediaWireless property.
     * 
     * @return
     *     possible object is
     *     {@link NULL }
     *     
     */
    public NULL getMultimediaWireless() {
        return multimediaWireless;
    }

    /**
     * Sets the value of the multimediaWireless property.
     * 
     * @param value
     *     allowed object is
     *     {@link NULL }
     *     
     */
    public void setMultimediaWireless(NULL value) {
        this.multimediaWireless = value;
    }

    /**
     * Gets the value of the multimediaNetworkIndependent property.
     * 
     * @return
     *     possible object is
     *     {@link NULL }
     *     
     */
    public NULL getMultimediaNetworkIndependent() {
        return multimediaNetworkIndependent;
    }

    /**
     * Sets the value of the multimediaNetworkIndependent property.
     * 
     * @param value
     *     allowed object is
     *     {@link NULL }
     *     
     */
    public void setMultimediaNetworkIndependent(NULL value) {
        this.multimediaNetworkIndependent = value;
    }

}
