//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.14 at 10:55:58 AM BST 
//


package org.etsi.uri._02657.v1_7_1_.retaineddata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

import org.etsi.uri._02657.v1_1_1_.retaineddata.AddressInformation;
import org.etsi.uri._02657.v1_1_1_.retaineddata.GSMLocation;


/**
 * <p>Java class for Spot complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Spot">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="gsmLocation" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}GSMLocation"/>
 *         &lt;element name="postalLocation" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}AddressInformation"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Spot", propOrder = {
    "gsmLocation",
    "postalLocation"
})
public class Spot {

    protected GSMLocation gsmLocation;
    protected AddressInformation postalLocation;

    /**
     * Gets the value of the gsmLocation property.
     * 
     * @return
     *     possible object is
     *     {@link GSMLocation }
     *     
     */
    public GSMLocation getGsmLocation() {
        return gsmLocation;
    }

    /**
     * Sets the value of the gsmLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link GSMLocation }
     *     
     */
    public void setGsmLocation(GSMLocation value) {
        this.gsmLocation = value;
    }

    /**
     * Gets the value of the postalLocation property.
     * 
     * @return
     *     possible object is
     *     {@link AddressInformation }
     *     
     */
    public AddressInformation getPostalLocation() {
        return postalLocation;
    }

    /**
     * Sets the value of the postalLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressInformation }
     *     
     */
    public void setPostalLocation(AddressInformation value) {
        this.postalLocation = value;
    }

}
