//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.14 at 10:55:58 AM BST 
//


package org.etsi.uri._02657.v1_7_1_.retaineddata;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import org.etsi.uri._02657.v1_1_1_.retaineddata.AddressInformation;
import org.etsi.uri._02657.v1_1_1_.retaineddata.TimeSpan;


/**
 * <p>Java class for SubscribedMultimediaServices complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubscribedMultimediaServices">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="serviceID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="providerID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="timeSpan" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}TimeSpan" minOccurs="0"/>
 *         &lt;element name="registeredIdentifiers" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="PartyIdentity" type="{http://uri.etsi.org/02657/v1.7.1#/RetainedData}PartyIdentity"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="registeredICCID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="serviceType" type="{http://uri.etsi.org/02657/v1.7.1#/RetainedData}MultimediaServiceType" minOccurs="0"/>
 *         &lt;element name="installationAddress" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}AddressInformation" minOccurs="0"/>
 *         &lt;element name="connectionDate" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}GeneralizedTime" minOccurs="0"/>
 *         &lt;element name="iMSI" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}IMSI" minOccurs="0"/>
 *         &lt;element name="carrierPreselect" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="lineStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nationalMultimediaServices" type="{http://uri.etsi.org/02657/v1.7.1#/RetainedData}NationalMultimediaServices" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubscribedMultimediaServices", propOrder = {
    "serviceID",
    "providerID",
    "timeSpan",
    "registeredIdentifiers",
    "registeredICCID",
    "serviceType",
    "installationAddress",
    "connectionDate",
    "imsi",
    "carrierPreselect",
    "lineStatus",
    "nationalMultimediaServices"
})
public class SubscribedMultimediaServices {

    protected String serviceID;
    protected String providerID;
    protected TimeSpan timeSpan;
    protected SubscribedMultimediaServices.RegisteredIdentifiers registeredIdentifiers;
    protected String registeredICCID;
    protected MultimediaServiceType serviceType;
    protected AddressInformation installationAddress;
    protected String connectionDate;
    @XmlElement(name = "iMSI", type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] imsi;
    protected Boolean carrierPreselect;
    protected String lineStatus;
    protected NationalMultimediaServices nationalMultimediaServices;

    /**
     * Gets the value of the serviceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceID() {
        return serviceID;
    }

    /**
     * Sets the value of the serviceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceID(String value) {
        this.serviceID = value;
    }

    /**
     * Gets the value of the providerID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderID() {
        return providerID;
    }

    /**
     * Sets the value of the providerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderID(String value) {
        this.providerID = value;
    }

    /**
     * Gets the value of the timeSpan property.
     * 
     * @return
     *     possible object is
     *     {@link TimeSpan }
     *     
     */
    public TimeSpan getTimeSpan() {
        return timeSpan;
    }

    /**
     * Sets the value of the timeSpan property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeSpan }
     *     
     */
    public void setTimeSpan(TimeSpan value) {
        this.timeSpan = value;
    }

    /**
     * Gets the value of the registeredIdentifiers property.
     * 
     * @return
     *     possible object is
     *     {@link SubscribedMultimediaServices.RegisteredIdentifiers }
     *     
     */
    public SubscribedMultimediaServices.RegisteredIdentifiers getRegisteredIdentifiers() {
        return registeredIdentifiers;
    }

    /**
     * Sets the value of the registeredIdentifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubscribedMultimediaServices.RegisteredIdentifiers }
     *     
     */
    public void setRegisteredIdentifiers(SubscribedMultimediaServices.RegisteredIdentifiers value) {
        this.registeredIdentifiers = value;
    }

    /**
     * Gets the value of the registeredICCID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegisteredICCID() {
        return registeredICCID;
    }

    /**
     * Sets the value of the registeredICCID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegisteredICCID(String value) {
        this.registeredICCID = value;
    }

    /**
     * Gets the value of the serviceType property.
     * 
     * @return
     *     possible object is
     *     {@link MultimediaServiceType }
     *     
     */
    public MultimediaServiceType getServiceType() {
        return serviceType;
    }

    /**
     * Sets the value of the serviceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultimediaServiceType }
     *     
     */
    public void setServiceType(MultimediaServiceType value) {
        this.serviceType = value;
    }

    /**
     * Gets the value of the installationAddress property.
     * 
     * @return
     *     possible object is
     *     {@link AddressInformation }
     *     
     */
    public AddressInformation getInstallationAddress() {
        return installationAddress;
    }

    /**
     * Sets the value of the installationAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressInformation }
     *     
     */
    public void setInstallationAddress(AddressInformation value) {
        this.installationAddress = value;
    }

    /**
     * Gets the value of the connectionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConnectionDate() {
        return connectionDate;
    }

    /**
     * Sets the value of the connectionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConnectionDate(String value) {
        this.connectionDate = value;
    }

    /**
     * Gets the value of the imsi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getIMSI() {
        return imsi;
    }

    /**
     * Sets the value of the imsi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIMSI(byte[] value) {
        this.imsi = ((byte[]) value);
    }

    /**
     * Gets the value of the carrierPreselect property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCarrierPreselect() {
        return carrierPreselect;
    }

    /**
     * Sets the value of the carrierPreselect property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCarrierPreselect(Boolean value) {
        this.carrierPreselect = value;
    }

    /**
     * Gets the value of the lineStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineStatus() {
        return lineStatus;
    }

    /**
     * Sets the value of the lineStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineStatus(String value) {
        this.lineStatus = value;
    }

    /**
     * Gets the value of the nationalMultimediaServices property.
     * 
     * @return
     *     possible object is
     *     {@link NationalMultimediaServices }
     *     
     */
    public NationalMultimediaServices getNationalMultimediaServices() {
        return nationalMultimediaServices;
    }

    /**
     * Sets the value of the nationalMultimediaServices property.
     * 
     * @param value
     *     allowed object is
     *     {@link NationalMultimediaServices }
     *     
     */
    public void setNationalMultimediaServices(NationalMultimediaServices value) {
        this.nationalMultimediaServices = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="PartyIdentity" type="{http://uri.etsi.org/02657/v1.7.1#/RetainedData}PartyIdentity"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "partyIdentity"
    })
    public static class RegisteredIdentifiers {

        @XmlElement(name = "PartyIdentity")
        protected List<String> partyIdentity;

        /**
         * Gets the value of the partyIdentity property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the partyIdentity property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPartyIdentity().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getPartyIdentity() {
            if (partyIdentity == null) {
                partyIdentity = new ArrayList<String>();
            }
            return this.partyIdentity;
        }

    }

}
