//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.18 at 03:38:40 PM GMT 
//


package com.ctg.dms.customerprofile.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{http://www.three.co.uk/midus/getcustomerdetails/bw/responseschema}EMAIL_ADDRESS" minOccurs="0"/>
 *         &lt;element ref="{http://www.three.co.uk/midus/getcustomerdetails/bw/responseschema}PRIMARY" minOccurs="0"/>
 *         &lt;element ref="{http://www.three.co.uk/midus/getcustomerdetails/bw/responseschema}PURPOSE_TYPE" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "EMAIL")
public class EMAIL {

    @XmlElement(name = "EMAIL_ADDRESS")
    protected String emailADDRESS;
    @XmlElement(name = "PRIMARY")
    protected String primary;
    @XmlElement(name = "PURPOSE_TYPE")
    protected String purposeTYPE;

    /**
     * Gets the value of the email_ADDRESS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEMAIL_ADDRESS() {
        return emailADDRESS;
    }

    /**
     * Sets the value of the email_ADDRESS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEMAIL_ADDRESS(String value) {
        this.emailADDRESS = value;
    }

    /**
     * Gets the value of the primary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRIMARY() {
        return primary;
    }

    /**
     * Sets the value of the primary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRIMARY(String value) {
        this.primary = value;
    }

    /**
     * Gets the value of the purpose_TYPE property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPURPOSE_TYPE() {
        return purposeTYPE;
    }

    /**
     * Sets the value of the purpose_TYPE property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPURPOSE_TYPE(String value) {
        this.purposeTYPE = value;
    }

	public String getEmailADDRESS() {
		return emailADDRESS;
	}

	public void setEmailADDRESS(String emailADDRESS) {
		this.emailADDRESS = emailADDRESS;
	}

	public String getPrimary() {
		return primary;
	}

	public void setPrimary(String primary) {
		this.primary = primary;
	}

	public String getPurposeTYPE() {
		return purposeTYPE;
	}

	public void setPurposeTYPE(String purposeTYPE) {
		this.purposeTYPE = purposeTYPE;
	}

}
