//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.18 at 03:38:40 PM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.three.co.uk/midus/getcustomerdetails/bw/responseschema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ctg.dms.customerprofile.response;
