//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.14 at 10:55:58 AM BST 
//


package org.etsi.uri._02657.v1_1_1_.retaineddata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CallForwardingEventType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CallForwardingEventType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="cfuActivation" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *         &lt;element name="cfuModification" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *         &lt;element name="cfuDe-activation" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *         &lt;element name="cfcNoReplyActivation" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *         &lt;element name="cfcNoReplyModification" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *         &lt;element name="cfcNoReplyDe-activation" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *         &lt;element name="cfcBusyActivation" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *         &lt;element name="cfcBusyModification" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *         &lt;element name="cfcBusyDe-activation" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *         &lt;element name="cfcOutOfRangeActivation" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *         &lt;element name="cfcOutOfRangeModification" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *         &lt;element name="cfcOutOfRangeDe-activation" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *         &lt;element name="cfcUnavailableActivation" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *         &lt;element name="cfcUnavailableModification" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *         &lt;element name="cfcUnavailableDe-activation" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *         &lt;element name="cfuFaxActivation" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *         &lt;element name="cfuFaxModification" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *         &lt;element name="cfuFaxDe-activation" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CallForwardingEventType", propOrder = {
    "cfuActivation",
    "cfuModification",
    "cfuDeActivation",
    "cfcNoReplyActivation",
    "cfcNoReplyModification",
    "cfcNoReplyDeActivation",
    "cfcBusyActivation",
    "cfcBusyModification",
    "cfcBusyDeActivation",
    "cfcOutOfRangeActivation",
    "cfcOutOfRangeModification",
    "cfcOutOfRangeDeActivation",
    "cfcUnavailableActivation",
    "cfcUnavailableModification",
    "cfcUnavailableDeActivation",
    "cfuFaxActivation",
    "cfuFaxModification",
    "cfuFaxDeActivation"
})
public class CallForwardingEventType {

    protected NULL cfuActivation;
    protected NULL cfuModification;
    @XmlElement(name = "cfuDe-activation")
    protected NULL cfuDeActivation;
    protected NULL cfcNoReplyActivation;
    protected NULL cfcNoReplyModification;
    @XmlElement(name = "cfcNoReplyDe-activation")
    protected NULL cfcNoReplyDeActivation;
    protected NULL cfcBusyActivation;
    protected NULL cfcBusyModification;
    @XmlElement(name = "cfcBusyDe-activation")
    protected NULL cfcBusyDeActivation;
    protected NULL cfcOutOfRangeActivation;
    protected NULL cfcOutOfRangeModification;
    @XmlElement(name = "cfcOutOfRangeDe-activation")
    protected NULL cfcOutOfRangeDeActivation;
    protected NULL cfcUnavailableActivation;
    protected NULL cfcUnavailableModification;
    @XmlElement(name = "cfcUnavailableDe-activation")
    protected NULL cfcUnavailableDeActivation;
    protected NULL cfuFaxActivation;
    protected NULL cfuFaxModification;
    @XmlElement(name = "cfuFaxDe-activation")
    protected NULL cfuFaxDeActivation;

    /**
     * Gets the value of the cfuActivation property.
     * 
     * @return
     *     possible object is
     *     {@link NULL }
     *     
     */
    public NULL getCfuActivation() {
        return cfuActivation;
    }

    /**
     * Sets the value of the cfuActivation property.
     * 
     * @param value
     *     allowed object is
     *     {@link NULL }
     *     
     */
    public void setCfuActivation(NULL value) {
        this.cfuActivation = value;
    }

    /**
     * Gets the value of the cfuModification property.
     * 
     * @return
     *     possible object is
     *     {@link NULL }
     *     
     */
    public NULL getCfuModification() {
        return cfuModification;
    }

    /**
     * Sets the value of the cfuModification property.
     * 
     * @param value
     *     allowed object is
     *     {@link NULL }
     *     
     */
    public void setCfuModification(NULL value) {
        this.cfuModification = value;
    }

    /**
     * Gets the value of the cfuDeActivation property.
     * 
     * @return
     *     possible object is
     *     {@link NULL }
     *     
     */
    public NULL getCfuDeActivation() {
        return cfuDeActivation;
    }

    /**
     * Sets the value of the cfuDeActivation property.
     * 
     * @param value
     *     allowed object is
     *     {@link NULL }
     *     
     */
    public void setCfuDeActivation(NULL value) {
        this.cfuDeActivation = value;
    }

    /**
     * Gets the value of the cfcNoReplyActivation property.
     * 
     * @return
     *     possible object is
     *     {@link NULL }
     *     
     */
    public NULL getCfcNoReplyActivation() {
        return cfcNoReplyActivation;
    }

    /**
     * Sets the value of the cfcNoReplyActivation property.
     * 
     * @param value
     *     allowed object is
     *     {@link NULL }
     *     
     */
    public void setCfcNoReplyActivation(NULL value) {
        this.cfcNoReplyActivation = value;
    }

    /**
     * Gets the value of the cfcNoReplyModification property.
     * 
     * @return
     *     possible object is
     *     {@link NULL }
     *     
     */
    public NULL getCfcNoReplyModification() {
        return cfcNoReplyModification;
    }

    /**
     * Sets the value of the cfcNoReplyModification property.
     * 
     * @param value
     *     allowed object is
     *     {@link NULL }
     *     
     */
    public void setCfcNoReplyModification(NULL value) {
        this.cfcNoReplyModification = value;
    }

    /**
     * Gets the value of the cfcNoReplyDeActivation property.
     * 
     * @return
     *     possible object is
     *     {@link NULL }
     *     
     */
    public NULL getCfcNoReplyDeActivation() {
        return cfcNoReplyDeActivation;
    }

    /**
     * Sets the value of the cfcNoReplyDeActivation property.
     * 
     * @param value
     *     allowed object is
     *     {@link NULL }
     *     
     */
    public void setCfcNoReplyDeActivation(NULL value) {
        this.cfcNoReplyDeActivation = value;
    }

    /**
     * Gets the value of the cfcBusyActivation property.
     * 
     * @return
     *     possible object is
     *     {@link NULL }
     *     
     */
    public NULL getCfcBusyActivation() {
        return cfcBusyActivation;
    }

    /**
     * Sets the value of the cfcBusyActivation property.
     * 
     * @param value
     *     allowed object is
     *     {@link NULL }
     *     
     */
    public void setCfcBusyActivation(NULL value) {
        this.cfcBusyActivation = value;
    }

    /**
     * Gets the value of the cfcBusyModification property.
     * 
     * @return
     *     possible object is
     *     {@link NULL }
     *     
     */
    public NULL getCfcBusyModification() {
        return cfcBusyModification;
    }

    /**
     * Sets the value of the cfcBusyModification property.
     * 
     * @param value
     *     allowed object is
     *     {@link NULL }
     *     
     */
    public void setCfcBusyModification(NULL value) {
        this.cfcBusyModification = value;
    }

    /**
     * Gets the value of the cfcBusyDeActivation property.
     * 
     * @return
     *     possible object is
     *     {@link NULL }
     *     
     */
    public NULL getCfcBusyDeActivation() {
        return cfcBusyDeActivation;
    }

    /**
     * Sets the value of the cfcBusyDeActivation property.
     * 
     * @param value
     *     allowed object is
     *     {@link NULL }
     *     
     */
    public void setCfcBusyDeActivation(NULL value) {
        this.cfcBusyDeActivation = value;
    }

    /**
     * Gets the value of the cfcOutOfRangeActivation property.
     * 
     * @return
     *     possible object is
     *     {@link NULL }
     *     
     */
    public NULL getCfcOutOfRangeActivation() {
        return cfcOutOfRangeActivation;
    }

    /**
     * Sets the value of the cfcOutOfRangeActivation property.
     * 
     * @param value
     *     allowed object is
     *     {@link NULL }
     *     
     */
    public void setCfcOutOfRangeActivation(NULL value) {
        this.cfcOutOfRangeActivation = value;
    }

    /**
     * Gets the value of the cfcOutOfRangeModification property.
     * 
     * @return
     *     possible object is
     *     {@link NULL }
     *     
     */
    public NULL getCfcOutOfRangeModification() {
        return cfcOutOfRangeModification;
    }

    /**
     * Sets the value of the cfcOutOfRangeModification property.
     * 
     * @param value
     *     allowed object is
     *     {@link NULL }
     *     
     */
    public void setCfcOutOfRangeModification(NULL value) {
        this.cfcOutOfRangeModification = value;
    }

    /**
     * Gets the value of the cfcOutOfRangeDeActivation property.
     * 
     * @return
     *     possible object is
     *     {@link NULL }
     *     
     */
    public NULL getCfcOutOfRangeDeActivation() {
        return cfcOutOfRangeDeActivation;
    }

    /**
     * Sets the value of the cfcOutOfRangeDeActivation property.
     * 
     * @param value
     *     allowed object is
     *     {@link NULL }
     *     
     */
    public void setCfcOutOfRangeDeActivation(NULL value) {
        this.cfcOutOfRangeDeActivation = value;
    }

    /**
     * Gets the value of the cfcUnavailableActivation property.
     * 
     * @return
     *     possible object is
     *     {@link NULL }
     *     
     */
    public NULL getCfcUnavailableActivation() {
        return cfcUnavailableActivation;
    }

    /**
     * Sets the value of the cfcUnavailableActivation property.
     * 
     * @param value
     *     allowed object is
     *     {@link NULL }
     *     
     */
    public void setCfcUnavailableActivation(NULL value) {
        this.cfcUnavailableActivation = value;
    }

    /**
     * Gets the value of the cfcUnavailableModification property.
     * 
     * @return
     *     possible object is
     *     {@link NULL }
     *     
     */
    public NULL getCfcUnavailableModification() {
        return cfcUnavailableModification;
    }

    /**
     * Sets the value of the cfcUnavailableModification property.
     * 
     * @param value
     *     allowed object is
     *     {@link NULL }
     *     
     */
    public void setCfcUnavailableModification(NULL value) {
        this.cfcUnavailableModification = value;
    }

    /**
     * Gets the value of the cfcUnavailableDeActivation property.
     * 
     * @return
     *     possible object is
     *     {@link NULL }
     *     
     */
    public NULL getCfcUnavailableDeActivation() {
        return cfcUnavailableDeActivation;
    }

    /**
     * Sets the value of the cfcUnavailableDeActivation property.
     * 
     * @param value
     *     allowed object is
     *     {@link NULL }
     *     
     */
    public void setCfcUnavailableDeActivation(NULL value) {
        this.cfcUnavailableDeActivation = value;
    }

    /**
     * Gets the value of the cfuFaxActivation property.
     * 
     * @return
     *     possible object is
     *     {@link NULL }
     *     
     */
    public NULL getCfuFaxActivation() {
        return cfuFaxActivation;
    }

    /**
     * Sets the value of the cfuFaxActivation property.
     * 
     * @param value
     *     allowed object is
     *     {@link NULL }
     *     
     */
    public void setCfuFaxActivation(NULL value) {
        this.cfuFaxActivation = value;
    }

    /**
     * Gets the value of the cfuFaxModification property.
     * 
     * @return
     *     possible object is
     *     {@link NULL }
     *     
     */
    public NULL getCfuFaxModification() {
        return cfuFaxModification;
    }

    /**
     * Sets the value of the cfuFaxModification property.
     * 
     * @param value
     *     allowed object is
     *     {@link NULL }
     *     
     */
    public void setCfuFaxModification(NULL value) {
        this.cfuFaxModification = value;
    }

    /**
     * Gets the value of the cfuFaxDeActivation property.
     * 
     * @return
     *     possible object is
     *     {@link NULL }
     *     
     */
    public NULL getCfuFaxDeActivation() {
        return cfuFaxDeActivation;
    }

    /**
     * Sets the value of the cfuFaxDeActivation property.
     * 
     * @param value
     *     allowed object is
     *     {@link NULL }
     *     
     */
    public void setCfuFaxDeActivation(NULL value) {
        this.cfuFaxDeActivation = value;
    }

}
