//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.14 at 10:55:58 AM BST 
//


package org.etsi.uri._02657.v1_1_1_.retaineddata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GeographicalCoordinates complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GeographicalCoordinates">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="latitudeSign" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="north" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *                   &lt;element name="south" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="latitude" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedInt">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="8388607"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="longitude" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="-8388608"/>
 *               &lt;maxInclusive value="8388607"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GeographicalCoordinates", propOrder = {
    "latitudeSign",
    "latitude",
    "longitude"
})
public class GeographicalCoordinates {

    protected GeographicalCoordinates.LatitudeSign latitudeSign;
    protected Long latitude;
    protected Integer longitude;

    /**
     * Gets the value of the latitudeSign property.
     * 
     * @return
     *     possible object is
     *     {@link GeographicalCoordinates.LatitudeSign }
     *     
     */
    public GeographicalCoordinates.LatitudeSign getLatitudeSign() {
        return latitudeSign;
    }

    /**
     * Sets the value of the latitudeSign property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeographicalCoordinates.LatitudeSign }
     *     
     */
    public void setLatitudeSign(GeographicalCoordinates.LatitudeSign value) {
        this.latitudeSign = value;
    }

    /**
     * Gets the value of the latitude property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getLatitude() {
        return latitude;
    }

    /**
     * Sets the value of the latitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLatitude(Long value) {
        this.latitude = value;
    }

    /**
     * Gets the value of the longitude property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLongitude() {
        return longitude;
    }

    /**
     * Sets the value of the longitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLongitude(Integer value) {
        this.longitude = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="north" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
     *         &lt;element name="south" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "north",
        "south"
    })
    public static class LatitudeSign {

        protected NULL north;
        protected NULL south;

        /**
         * Gets the value of the north property.
         * 
         * @return
         *     possible object is
         *     {@link NULL }
         *     
         */
        public NULL getNorth() {
            return north;
        }

        /**
         * Sets the value of the north property.
         * 
         * @param value
         *     allowed object is
         *     {@link NULL }
         *     
         */
        public void setNorth(NULL value) {
            this.north = value;
        }

        /**
         * Gets the value of the south property.
         * 
         * @return
         *     possible object is
         *     {@link NULL }
         *     
         */
        public NULL getSouth() {
            return south;
        }

        /**
         * Sets the value of the south property.
         * 
         * @param value
         *     allowed object is
         *     {@link NULL }
         *     
         */
        public void setSouth(NULL value) {
            this.south = value;
        }

    }

}
