//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.14 at 10:55:58 AM BST 
//


package org.etsi.uri._02657.v1_1_1_.retaineddata;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import org.etsi.uri._02657.v1_3_1_1.retaineddata.GPRSEvent;


/**
 * <p>Java class for GprsInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GprsInformation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="iMSI" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}IMSI" minOccurs="0"/>
 *         &lt;element name="mSISDN" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}PartyNumber" minOccurs="0"/>
 *         &lt;element name="sgsnAddress" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="IPAddress" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}IPAddress"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ggsnAddress" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}IPAddress" minOccurs="0"/>
 *         &lt;element name="pDP_address_allocated" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}IPAddress" minOccurs="0"/>
 *         &lt;element name="aPN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pDP_type" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}hexBinary">
 *               &lt;length value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{http://uri.etsi.org/02657/v1.3.1#1/RetainedData}gPRSEvent" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/02657/v1.7.1#/RetainedData}iCCID" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GprsInformation", propOrder = {
    "imsi",
    "msisdn",
    "sgsnAddress",
    "ggsnAddress",
    "pdpAddressAllocated",
    "apn",
    "pdpType",
    "gprsEvent",
    "iccid"
})
public class GprsInformation {

    @XmlElement(name = "iMSI", type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] imsi;
    @XmlElement(name = "mSISDN")
    protected String msisdn;
    protected GprsInformation.SgsnAddress sgsnAddress;
    protected IPAddress ggsnAddress;
    @XmlElement(name = "pDP_address_allocated")
    protected IPAddress pdpAddressAllocated;
    @XmlElement(name = "aPN")
    protected String apn;
    @XmlElement(name = "pDP_type", type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] pdpType;
    @XmlElement(name = "gPRSEvent", namespace = "http://uri.etsi.org/02657/v1.3.1#1/RetainedData")
    protected GPRSEvent gprsEvent;
    @XmlElement(name = "iCCID", namespace = "http://uri.etsi.org/02657/v1.7.1#/RetainedData")
    protected String iccid;

    /**
     * Gets the value of the imsi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getIMSI() {
        return imsi;
    }

    /**
     * Sets the value of the imsi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIMSI(byte[] value) {
        this.imsi = ((byte[]) value);
    }

    /**
     * Gets the value of the msisdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMSISDN() {
        return msisdn;
    }

    /**
     * Sets the value of the msisdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMSISDN(String value) {
        this.msisdn = value;
    }

    /**
     * Gets the value of the sgsnAddress property.
     * 
     * @return
     *     possible object is
     *     {@link GprsInformation.SgsnAddress }
     *     
     */
    public GprsInformation.SgsnAddress getSgsnAddress() {
        return sgsnAddress;
    }

    /**
     * Sets the value of the sgsnAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link GprsInformation.SgsnAddress }
     *     
     */
    public void setSgsnAddress(GprsInformation.SgsnAddress value) {
        this.sgsnAddress = value;
    }

    /**
     * Gets the value of the ggsnAddress property.
     * 
     * @return
     *     possible object is
     *     {@link IPAddress }
     *     
     */
    public IPAddress getGgsnAddress() {
        return ggsnAddress;
    }

    /**
     * Sets the value of the ggsnAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link IPAddress }
     *     
     */
    public void setGgsnAddress(IPAddress value) {
        this.ggsnAddress = value;
    }

    /**
     * Gets the value of the pdpAddressAllocated property.
     * 
     * @return
     *     possible object is
     *     {@link IPAddress }
     *     
     */
    public IPAddress getPDPAddressAllocated() {
        return pdpAddressAllocated;
    }

    /**
     * Sets the value of the pdpAddressAllocated property.
     * 
     * @param value
     *     allowed object is
     *     {@link IPAddress }
     *     
     */
    public void setPDPAddressAllocated(IPAddress value) {
        this.pdpAddressAllocated = value;
    }

    /**
     * Gets the value of the apn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPN() {
        return apn;
    }

    /**
     * Sets the value of the apn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPN(String value) {
        this.apn = value;
    }

    /**
     * Gets the value of the pdpType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getPDPType() {
        return pdpType;
    }

    /**
     * Sets the value of the pdpType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPDPType(byte[] value) {
        this.pdpType = ((byte[]) value);
    }

    /**
     * Gets the value of the gprsEvent property.
     * 
     * @return
     *     possible object is
     *     {@link GPRSEvent }
     *     
     */
    public GPRSEvent getGPRSEvent() {
        return gprsEvent;
    }

    /**
     * Sets the value of the gprsEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link GPRSEvent }
     *     
     */
    public void setGPRSEvent(GPRSEvent value) {
        this.gprsEvent = value;
    }

    /**
     * Gets the value of the iccid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getICCID() {
        return iccid;
    }

    /**
     * Sets the value of the iccid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setICCID(String value) {
        this.iccid = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="IPAddress" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}IPAddress"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ipAddress"
    })
    public static class SgsnAddress {

        @XmlElement(name = "IPAddress")
        protected List<IPAddress> ipAddress;

        /**
         * Gets the value of the ipAddress property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the ipAddress property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIPAddress().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link IPAddress }
         * 
         * 
         */
        public List<IPAddress> getIPAddress() {
            if (ipAddress == null) {
                ipAddress = new ArrayList<IPAddress>();
            }
            return this.ipAddress;
        }

    }

}
