//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.14 at 10:55:58 AM BST 
//


package org.etsi.uri._02657.v1_1_1_.retaineddata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import org.etsi.uri._02657.v1_7_1_.retaineddata.ExtendedLocation;


/**
 * <p>Java class for Location complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Location">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="e164_Number" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}hexBinary">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="globalCellID" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}hexBinary">
 *               &lt;minLength value="5"/>
 *               &lt;maxLength value="7"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="rAI" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}hexBinary">
 *               &lt;length value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="gsmLocation" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}GSMLocation" minOccurs="0"/>
 *         &lt;element name="umtsLocation" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}UMTSLocation" minOccurs="0"/>
 *         &lt;element name="sAI" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}hexBinary">
 *               &lt;length value="7"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="oldRAI" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}hexBinary">
 *               &lt;length value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{http://uri.etsi.org/02657/v1.3.1#1/RetainedData}postalLocation" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/02657/v1.7.1#/RetainedData}extendedLocation" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Location", propOrder = {
    "e164Number",
    "globalCellID",
    "rai",
    "gsmLocation",
    "umtsLocation",
    "sai",
    "oldRAI",
    "postalLocation",
    "extendedLocation"
})
public class Location {

    @XmlElement(name = "e164_Number", type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] e164Number;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] globalCellID;
    @XmlElement(name = "rAI", type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] rai;
    protected GSMLocation gsmLocation;
    protected UMTSLocation umtsLocation;
    @XmlElement(name = "sAI", type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] sai;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] oldRAI;
    @XmlElement(namespace = "http://uri.etsi.org/02657/v1.3.1#1/RetainedData")
    protected AddressInformation postalLocation;
    @XmlElement(namespace = "http://uri.etsi.org/02657/v1.7.1#/RetainedData")
    protected ExtendedLocation extendedLocation;

    /**
     * Gets the value of the e164Number property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getE164Number() {
        return e164Number;
    }

    /**
     * Sets the value of the e164Number property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setE164Number(byte[] value) {
        this.e164Number = ((byte[]) value);
    }

    /**
     * Gets the value of the globalCellID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getGlobalCellID() {
        return globalCellID;
    }

    /**
     * Sets the value of the globalCellID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGlobalCellID(byte[] value) {
        this.globalCellID = ((byte[]) value);
    }

    /**
     * Gets the value of the rai property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getRAI() {
        return rai;
    }

    /**
     * Sets the value of the rai property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRAI(byte[] value) {
        this.rai = ((byte[]) value);
    }

    /**
     * Gets the value of the gsmLocation property.
     * 
     * @return
     *     possible object is
     *     {@link GSMLocation }
     *     
     */
    public GSMLocation getGsmLocation() {
        return gsmLocation;
    }

    /**
     * Sets the value of the gsmLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link GSMLocation }
     *     
     */
    public void setGsmLocation(GSMLocation value) {
        this.gsmLocation = value;
    }

    /**
     * Gets the value of the umtsLocation property.
     * 
     * @return
     *     possible object is
     *     {@link UMTSLocation }
     *     
     */
    public UMTSLocation getUmtsLocation() {
        return umtsLocation;
    }

    /**
     * Sets the value of the umtsLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link UMTSLocation }
     *     
     */
    public void setUmtsLocation(UMTSLocation value) {
        this.umtsLocation = value;
    }

    /**
     * Gets the value of the sai property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getSAI() {
        return sai;
    }

    /**
     * Sets the value of the sai property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSAI(byte[] value) {
        this.sai = ((byte[]) value);
    }

    /**
     * Gets the value of the oldRAI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getOldRAI() {
        return oldRAI;
    }

    /**
     * Sets the value of the oldRAI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOldRAI(byte[] value) {
        this.oldRAI = ((byte[]) value);
    }

    /**
     * Gets the value of the postalLocation property.
     * 
     * @return
     *     possible object is
     *     {@link AddressInformation }
     *     
     */
    public AddressInformation getPostalLocation() {
        return postalLocation;
    }

    /**
     * Sets the value of the postalLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressInformation }
     *     
     */
    public void setPostalLocation(AddressInformation value) {
        this.postalLocation = value;
    }

    /**
     * Gets the value of the extendedLocation property.
     * 
     * @return
     *     possible object is
     *     {@link ExtendedLocation }
     *     
     */
    public ExtendedLocation getExtendedLocation() {
        return extendedLocation;
    }

    /**
     * Sets the value of the extendedLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtendedLocation }
     *     
     */
    public void setExtendedLocation(ExtendedLocation value) {
        this.extendedLocation = value;
    }

}
