//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.14 at 10:55:58 AM BST 
//


package org.etsi.uri._02657.v1_1_1_.retaineddata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import org.etsi.uri._02657.v1_7_1_.retaineddata.MsgBillingDetails;


/**
 * <p>Java class for MessageRecord complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MessageRecord">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="msgSubscriber" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}MsgSubscriber"/>
 *         &lt;element name="msgServiceUsage" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}MsgServiceUsage"/>
 *         &lt;element ref="{http://uri.etsi.org/02657/v1.7.1#/RetainedData}msgBillingDetails"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MessageRecord", propOrder = {
    "msgSubscriber",
    "msgServiceUsage",
    "msgBillingDetails"
})
public class MessageRecord {

    protected MsgSubscriber msgSubscriber;
    protected MsgServiceUsage msgServiceUsage;
    @XmlElement(namespace = "http://uri.etsi.org/02657/v1.7.1#/RetainedData")
    protected MsgBillingDetails msgBillingDetails;

    /**
     * Gets the value of the msgSubscriber property.
     * 
     * @return
     *     possible object is
     *     {@link MsgSubscriber }
     *     
     */
    public MsgSubscriber getMsgSubscriber() {
        return msgSubscriber;
    }

    /**
     * Sets the value of the msgSubscriber property.
     * 
     * @param value
     *     allowed object is
     *     {@link MsgSubscriber }
     *     
     */
    public void setMsgSubscriber(MsgSubscriber value) {
        this.msgSubscriber = value;
    }

    /**
     * Gets the value of the msgServiceUsage property.
     * 
     * @return
     *     possible object is
     *     {@link MsgServiceUsage }
     *     
     */
    public MsgServiceUsage getMsgServiceUsage() {
        return msgServiceUsage;
    }

    /**
     * Sets the value of the msgServiceUsage property.
     * 
     * @param value
     *     allowed object is
     *     {@link MsgServiceUsage }
     *     
     */
    public void setMsgServiceUsage(MsgServiceUsage value) {
        this.msgServiceUsage = value;
    }

    /**
     * Gets the value of the msgBillingDetails property.
     * 
     * @return
     *     possible object is
     *     {@link MsgBillingDetails }
     *     
     */
    public MsgBillingDetails getMsgBillingDetails() {
        return msgBillingDetails;
    }

    /**
     * Sets the value of the msgBillingDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link MsgBillingDetails }
     *     
     */
    public void setMsgBillingDetails(MsgBillingDetails value) {
        this.msgBillingDetails = value;
    }

}
