//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.14 at 10:55:58 AM BST 
//


package org.etsi.uri._02657.v1_1_1_.retaineddata;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for MsgSubscriber complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MsgSubscriber">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="validity" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}TimeSpan" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/02657/v1.3.1#2/RetainedData}subscriberID" minOccurs="0"/>
 *         &lt;element name="msgStores" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="MsgStore" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}MsgStore"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="subscriber" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}GenericSubscriberInfo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MsgSubscriber", propOrder = {
    "validity",
    "subscriberID",
    "msgStores",
    "subscriber"
})
public class MsgSubscriber {

    protected TimeSpan validity;
    @XmlElement(namespace = "http://uri.etsi.org/02657/v1.3.1#2/RetainedData", type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] subscriberID;
    protected MsgSubscriber.MsgStores msgStores;
    protected GenericSubscriberInfo subscriber;

    /**
     * Gets the value of the validity property.
     * 
     * @return
     *     possible object is
     *     {@link TimeSpan }
     *     
     */
    public TimeSpan getValidity() {
        return validity;
    }

    /**
     * Sets the value of the validity property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeSpan }
     *     
     */
    public void setValidity(TimeSpan value) {
        this.validity = value;
    }

    /**
     * Gets the value of the subscriberID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getSubscriberID() {
        return subscriberID;
    }

    /**
     * Sets the value of the subscriberID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubscriberID(byte[] value) {
        this.subscriberID = ((byte[]) value);
    }

    /**
     * Gets the value of the msgStores property.
     * 
     * @return
     *     possible object is
     *     {@link MsgSubscriber.MsgStores }
     *     
     */
    public MsgSubscriber.MsgStores getMsgStores() {
        return msgStores;
    }

    /**
     * Sets the value of the msgStores property.
     * 
     * @param value
     *     allowed object is
     *     {@link MsgSubscriber.MsgStores }
     *     
     */
    public void setMsgStores(MsgSubscriber.MsgStores value) {
        this.msgStores = value;
    }

    /**
     * Gets the value of the subscriber property.
     * 
     * @return
     *     possible object is
     *     {@link GenericSubscriberInfo }
     *     
     */
    public GenericSubscriberInfo getSubscriber() {
        return subscriber;
    }

    /**
     * Sets the value of the subscriber property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericSubscriberInfo }
     *     
     */
    public void setSubscriber(GenericSubscriberInfo value) {
        this.subscriber = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="MsgStore" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}MsgStore"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "msgStore"
    })
    public static class MsgStores {

        @XmlElement(name = "MsgStore")
        protected List<MsgStore> msgStore;

        /**
         * Gets the value of the msgStore property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the msgStore property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMsgStore().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MsgStore }
         * 
         * 
         */
        public List<MsgStore> getMsgStore() {
            if (msgStore == null) {
                msgStore = new ArrayList<MsgStore>();
            }
            return this.msgStore;
        }

    }

}
