//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.14 at 10:55:58 AM BST 
//


package org.etsi.uri._02657.v1_1_1_.retaineddata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import org.etsi.uri._02657.v1_3_1_1.retaineddata.Recipients;


/**
 * <p>Java class for MsgStoreOperation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MsgStoreOperation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dateTime" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}GeneralizedTime" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/02657/v1.3.1#2/RetainedData}subscriberID" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/02657/v1.3.1#1/RetainedData}msgStore" minOccurs="0"/>
 *         &lt;element name="operation" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="connect" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *                   &lt;element name="disconnect" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *                   &lt;element name="retrieveMsg" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *                   &lt;element name="partialretrieveMsg" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *                   &lt;element name="deleteMsg" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *                   &lt;element name="addMsg" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *                   &lt;element ref="{http://uri.etsi.org/02657/v1.3.1#1/RetainedData}editMsg"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://uri.etsi.org/02657/v1.3.1#1/RetainedData}senderAddress" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/02657/v1.3.1#1/RetainedData}recipients" minOccurs="0"/>
 *         &lt;element name="protocol" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="pop" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *                   &lt;element name="imap" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *                   &lt;element ref="{http://uri.etsi.org/02657/v1.3.1#1/RetainedData}webmail"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="clientID" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}IPAddress" minOccurs="0"/>
 *         &lt;element name="serverID" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}IPAddress" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/02657/v1.3.1#1/RetainedData}messageID" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MsgStoreOperation", propOrder = {
    "dateTime",
    "subscriberID",
    "msgStore",
    "operation",
    "senderAddress",
    "recipients",
    "protocol",
    "clientID",
    "serverID",
    "messageID"
})
public class MsgStoreOperation {

    protected String dateTime;
    @XmlElement(namespace = "http://uri.etsi.org/02657/v1.3.1#2/RetainedData", type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] subscriberID;
    @XmlElement(namespace = "http://uri.etsi.org/02657/v1.3.1#1/RetainedData", type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] msgStore;
    protected MsgStoreOperation.Operation operation;
    @XmlElement(namespace = "http://uri.etsi.org/02657/v1.3.1#1/RetainedData")
    protected String senderAddress;
    @XmlElement(namespace = "http://uri.etsi.org/02657/v1.3.1#1/RetainedData")
    protected Recipients recipients;
    protected MsgStoreOperation.Protocol protocol;
    protected IPAddress clientID;
    protected IPAddress serverID;
    @XmlElement(namespace = "http://uri.etsi.org/02657/v1.3.1#1/RetainedData")
    protected String messageID;

    /**
     * Gets the value of the dateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateTime() {
        return dateTime;
    }

    /**
     * Sets the value of the dateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateTime(String value) {
        this.dateTime = value;
    }

    /**
     * Gets the value of the subscriberID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getSubscriberID() {
        return subscriberID;
    }

    /**
     * Sets the value of the subscriberID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubscriberID(byte[] value) {
        this.subscriberID = ((byte[]) value);
    }

    /**
     * Gets the value of the msgStore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getMsgStore() {
        return msgStore;
    }

    /**
     * Sets the value of the msgStore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgStore(byte[] value) {
        this.msgStore = ((byte[]) value);
    }

    /**
     * Gets the value of the operation property.
     * 
     * @return
     *     possible object is
     *     {@link MsgStoreOperation.Operation }
     *     
     */
    public MsgStoreOperation.Operation getOperation() {
        return operation;
    }

    /**
     * Sets the value of the operation property.
     * 
     * @param value
     *     allowed object is
     *     {@link MsgStoreOperation.Operation }
     *     
     */
    public void setOperation(MsgStoreOperation.Operation value) {
        this.operation = value;
    }

    /**
     * Gets the value of the senderAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderAddress() {
        return senderAddress;
    }

    /**
     * Sets the value of the senderAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderAddress(String value) {
        this.senderAddress = value;
    }

    /**
     * Gets the value of the recipients property.
     * 
     * @return
     *     possible object is
     *     {@link Recipients }
     *     
     */
    public Recipients getRecipients() {
        return recipients;
    }

    /**
     * Sets the value of the recipients property.
     * 
     * @param value
     *     allowed object is
     *     {@link Recipients }
     *     
     */
    public void setRecipients(Recipients value) {
        this.recipients = value;
    }

    /**
     * Gets the value of the protocol property.
     * 
     * @return
     *     possible object is
     *     {@link MsgStoreOperation.Protocol }
     *     
     */
    public MsgStoreOperation.Protocol getProtocol() {
        return protocol;
    }

    /**
     * Sets the value of the protocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link MsgStoreOperation.Protocol }
     *     
     */
    public void setProtocol(MsgStoreOperation.Protocol value) {
        this.protocol = value;
    }

    /**
     * Gets the value of the clientID property.
     * 
     * @return
     *     possible object is
     *     {@link IPAddress }
     *     
     */
    public IPAddress getClientID() {
        return clientID;
    }

    /**
     * Sets the value of the clientID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IPAddress }
     *     
     */
    public void setClientID(IPAddress value) {
        this.clientID = value;
    }

    /**
     * Gets the value of the serverID property.
     * 
     * @return
     *     possible object is
     *     {@link IPAddress }
     *     
     */
    public IPAddress getServerID() {
        return serverID;
    }

    /**
     * Sets the value of the serverID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IPAddress }
     *     
     */
    public void setServerID(IPAddress value) {
        this.serverID = value;
    }

    /**
     * Gets the value of the messageID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageID() {
        return messageID;
    }

    /**
     * Sets the value of the messageID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageID(String value) {
        this.messageID = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="connect" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
     *         &lt;element name="disconnect" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
     *         &lt;element name="retrieveMsg" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
     *         &lt;element name="partialretrieveMsg" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
     *         &lt;element name="deleteMsg" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
     *         &lt;element name="addMsg" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
     *         &lt;element ref="{http://uri.etsi.org/02657/v1.3.1#1/RetainedData}editMsg"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "connect",
        "disconnect",
        "retrieveMsg",
        "partialretrieveMsg",
        "deleteMsg",
        "addMsg",
        "editMsg"
    })
    public static class Operation {

        protected NULL connect;
        protected NULL disconnect;
        protected NULL retrieveMsg;
        protected NULL partialretrieveMsg;
        protected NULL deleteMsg;
        protected NULL addMsg;
        @XmlElement(namespace = "http://uri.etsi.org/02657/v1.3.1#1/RetainedData")
        protected NULL editMsg;

        /**
         * Gets the value of the connect property.
         * 
         * @return
         *     possible object is
         *     {@link NULL }
         *     
         */
        public NULL getConnect() {
            return connect;
        }

        /**
         * Sets the value of the connect property.
         * 
         * @param value
         *     allowed object is
         *     {@link NULL }
         *     
         */
        public void setConnect(NULL value) {
            this.connect = value;
        }

        /**
         * Gets the value of the disconnect property.
         * 
         * @return
         *     possible object is
         *     {@link NULL }
         *     
         */
        public NULL getDisconnect() {
            return disconnect;
        }

        /**
         * Sets the value of the disconnect property.
         * 
         * @param value
         *     allowed object is
         *     {@link NULL }
         *     
         */
        public void setDisconnect(NULL value) {
            this.disconnect = value;
        }

        /**
         * Gets the value of the retrieveMsg property.
         * 
         * @return
         *     possible object is
         *     {@link NULL }
         *     
         */
        public NULL getRetrieveMsg() {
            return retrieveMsg;
        }

        /**
         * Sets the value of the retrieveMsg property.
         * 
         * @param value
         *     allowed object is
         *     {@link NULL }
         *     
         */
        public void setRetrieveMsg(NULL value) {
            this.retrieveMsg = value;
        }

        /**
         * Gets the value of the partialretrieveMsg property.
         * 
         * @return
         *     possible object is
         *     {@link NULL }
         *     
         */
        public NULL getPartialretrieveMsg() {
            return partialretrieveMsg;
        }

        /**
         * Sets the value of the partialretrieveMsg property.
         * 
         * @param value
         *     allowed object is
         *     {@link NULL }
         *     
         */
        public void setPartialretrieveMsg(NULL value) {
            this.partialretrieveMsg = value;
        }

        /**
         * Gets the value of the deleteMsg property.
         * 
         * @return
         *     possible object is
         *     {@link NULL }
         *     
         */
        public NULL getDeleteMsg() {
            return deleteMsg;
        }

        /**
         * Sets the value of the deleteMsg property.
         * 
         * @param value
         *     allowed object is
         *     {@link NULL }
         *     
         */
        public void setDeleteMsg(NULL value) {
            this.deleteMsg = value;
        }

        /**
         * Gets the value of the addMsg property.
         * 
         * @return
         *     possible object is
         *     {@link NULL }
         *     
         */
        public NULL getAddMsg() {
            return addMsg;
        }

        /**
         * Sets the value of the addMsg property.
         * 
         * @param value
         *     allowed object is
         *     {@link NULL }
         *     
         */
        public void setAddMsg(NULL value) {
            this.addMsg = value;
        }

        /**
         * Gets the value of the editMsg property.
         * 
         * @return
         *     possible object is
         *     {@link NULL }
         *     
         */
        public NULL getEditMsg() {
            return editMsg;
        }

        /**
         * Sets the value of the editMsg property.
         * 
         * @param value
         *     allowed object is
         *     {@link NULL }
         *     
         */
        public void setEditMsg(NULL value) {
            this.editMsg = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="pop" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
     *         &lt;element name="imap" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
     *         &lt;element ref="{http://uri.etsi.org/02657/v1.3.1#1/RetainedData}webmail"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pop",
        "imap",
        "webmail"
    })
    public static class Protocol {

        protected NULL pop;
        protected NULL imap;
        @XmlElement(namespace = "http://uri.etsi.org/02657/v1.3.1#1/RetainedData")
        protected NULL webmail;

        /**
         * Gets the value of the pop property.
         * 
         * @return
         *     possible object is
         *     {@link NULL }
         *     
         */
        public NULL getPop() {
            return pop;
        }

        /**
         * Sets the value of the pop property.
         * 
         * @param value
         *     allowed object is
         *     {@link NULL }
         *     
         */
        public void setPop(NULL value) {
            this.pop = value;
        }

        /**
         * Gets the value of the imap property.
         * 
         * @return
         *     possible object is
         *     {@link NULL }
         *     
         */
        public NULL getImap() {
            return imap;
        }

        /**
         * Sets the value of the imap property.
         * 
         * @param value
         *     allowed object is
         *     {@link NULL }
         *     
         */
        public void setImap(NULL value) {
            this.imap = value;
        }

        /**
         * Gets the value of the webmail property.
         * 
         * @return
         *     possible object is
         *     {@link NULL }
         *     
         */
        public NULL getWebmail() {
            return webmail;
        }

        /**
         * Sets the value of the webmail property.
         * 
         * @param value
         *     allowed object is
         *     {@link NULL }
         *     
         */
        public void setWebmail(NULL value) {
            this.webmail = value;
        }

    }

}
