//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.14 at 10:55:58 AM BST 
//


package org.etsi.uri._02657.v1_1_1_.retaineddata;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NAAssignedAddress complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NAAssignedAddress">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="addressSetOrRangeOrMask" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}IPAddressSetOrRangeOrMask" minOccurs="0"/>
 *         &lt;element name="portNumber" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="addressType" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="unknown" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *                   &lt;element name="internal" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *                   &lt;element name="external" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="assignedTime" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}TimeSpan" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/02657/v1.3.1#1/RetainedData}destinationAddress" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/02657/v1.3.1#1/RetainedData}destinationPort" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NAAssignedAddress", propOrder = {
    "addressSetOrRangeOrMask",
    "portNumber",
    "addressType",
    "assignedTime",
    "destinationAddress",
    "destinationPort"
})
public class NAAssignedAddress {

    protected IPAddressSetOrRangeOrMask addressSetOrRangeOrMask;
    protected BigInteger portNumber;
    protected NAAssignedAddress.AddressType addressType;
    protected TimeSpan assignedTime;
    @XmlElement(namespace = "http://uri.etsi.org/02657/v1.3.1#1/RetainedData")
    protected IPAddress destinationAddress;
    @XmlElement(namespace = "http://uri.etsi.org/02657/v1.3.1#1/RetainedData")
    protected BigInteger destinationPort;

    /**
     * Gets the value of the addressSetOrRangeOrMask property.
     * 
     * @return
     *     possible object is
     *     {@link IPAddressSetOrRangeOrMask }
     *     
     */
    public IPAddressSetOrRangeOrMask getAddressSetOrRangeOrMask() {
        return addressSetOrRangeOrMask;
    }

    /**
     * Sets the value of the addressSetOrRangeOrMask property.
     * 
     * @param value
     *     allowed object is
     *     {@link IPAddressSetOrRangeOrMask }
     *     
     */
    public void setAddressSetOrRangeOrMask(IPAddressSetOrRangeOrMask value) {
        this.addressSetOrRangeOrMask = value;
    }

    /**
     * Gets the value of the portNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPortNumber() {
        return portNumber;
    }

    /**
     * Sets the value of the portNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPortNumber(BigInteger value) {
        this.portNumber = value;
    }

    /**
     * Gets the value of the addressType property.
     * 
     * @return
     *     possible object is
     *     {@link NAAssignedAddress.AddressType }
     *     
     */
    public NAAssignedAddress.AddressType getAddressType() {
        return addressType;
    }

    /**
     * Sets the value of the addressType property.
     * 
     * @param value
     *     allowed object is
     *     {@link NAAssignedAddress.AddressType }
     *     
     */
    public void setAddressType(NAAssignedAddress.AddressType value) {
        this.addressType = value;
    }

    /**
     * Gets the value of the assignedTime property.
     * 
     * @return
     *     possible object is
     *     {@link TimeSpan }
     *     
     */
    public TimeSpan getAssignedTime() {
        return assignedTime;
    }

    /**
     * Sets the value of the assignedTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeSpan }
     *     
     */
    public void setAssignedTime(TimeSpan value) {
        this.assignedTime = value;
    }

    /**
     * Gets the value of the destinationAddress property.
     * 
     * @return
     *     possible object is
     *     {@link IPAddress }
     *     
     */
    public IPAddress getDestinationAddress() {
        return destinationAddress;
    }

    /**
     * Sets the value of the destinationAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link IPAddress }
     *     
     */
    public void setDestinationAddress(IPAddress value) {
        this.destinationAddress = value;
    }

    /**
     * Gets the value of the destinationPort property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDestinationPort() {
        return destinationPort;
    }

    /**
     * Sets the value of the destinationPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDestinationPort(BigInteger value) {
        this.destinationPort = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="unknown" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
     *         &lt;element name="internal" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
     *         &lt;element name="external" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "unknown",
        "internal",
        "external"
    })
    public static class AddressType {

        protected NULL unknown;
        protected NULL internal;
        protected NULL external;

        /**
         * Gets the value of the unknown property.
         * 
         * @return
         *     possible object is
         *     {@link NULL }
         *     
         */
        public NULL getUnknown() {
            return unknown;
        }

        /**
         * Sets the value of the unknown property.
         * 
         * @param value
         *     allowed object is
         *     {@link NULL }
         *     
         */
        public void setUnknown(NULL value) {
            this.unknown = value;
        }

        /**
         * Gets the value of the internal property.
         * 
         * @return
         *     possible object is
         *     {@link NULL }
         *     
         */
        public NULL getInternal() {
            return internal;
        }

        /**
         * Sets the value of the internal property.
         * 
         * @param value
         *     allowed object is
         *     {@link NULL }
         *     
         */
        public void setInternal(NULL value) {
            this.internal = value;
        }

        /**
         * Gets the value of the external property.
         * 
         * @return
         *     possible object is
         *     {@link NULL }
         *     
         */
        public NULL getExternal() {
            return external;
        }

        /**
         * Sets the value of the external property.
         * 
         * @param value
         *     allowed object is
         *     {@link NULL }
         *     
         */
        public void setExternal(NULL value) {
            this.external = value;
        }

    }

}
