//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.14 at 10:55:58 AM BST 
//


package org.etsi.uri._02657.v1_1_1_.retaineddata;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NASubscriber complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NASubscriber">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="validity" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}TimeSpan" minOccurs="0"/>
 *         &lt;element name="subscriberID" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NaSubscriberID" minOccurs="0"/>
 *         &lt;element name="naSubscriptions" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="NAServiceSubscription" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NAServiceSubscription"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="allocatedDeviceIDs" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="NADeviceId" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NADeviceId"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="subscriber" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}GenericSubscriberInfo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NASubscriber", propOrder = {
    "validity",
    "subscriberID",
    "naSubscriptions",
    "allocatedDeviceIDs",
    "subscriber"
})
public class NASubscriber {

    protected TimeSpan validity;
    protected String subscriberID;
    protected NASubscriber.NaSubscriptions naSubscriptions;
    protected NASubscriber.AllocatedDeviceIDs allocatedDeviceIDs;
    protected GenericSubscriberInfo subscriber;

    /**
     * Gets the value of the validity property.
     * 
     * @return
     *     possible object is
     *     {@link TimeSpan }
     *     
     */
    public TimeSpan getValidity() {
        return validity;
    }

    /**
     * Sets the value of the validity property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeSpan }
     *     
     */
    public void setValidity(TimeSpan value) {
        this.validity = value;
    }

    /**
     * Gets the value of the subscriberID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubscriberID() {
        return subscriberID;
    }

    /**
     * Sets the value of the subscriberID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubscriberID(String value) {
        this.subscriberID = value;
    }

    /**
     * Gets the value of the naSubscriptions property.
     * 
     * @return
     *     possible object is
     *     {@link NASubscriber.NaSubscriptions }
     *     
     */
    public NASubscriber.NaSubscriptions getNaSubscriptions() {
        return naSubscriptions;
    }

    /**
     * Sets the value of the naSubscriptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link NASubscriber.NaSubscriptions }
     *     
     */
    public void setNaSubscriptions(NASubscriber.NaSubscriptions value) {
        this.naSubscriptions = value;
    }

    /**
     * Gets the value of the allocatedDeviceIDs property.
     * 
     * @return
     *     possible object is
     *     {@link NASubscriber.AllocatedDeviceIDs }
     *     
     */
    public NASubscriber.AllocatedDeviceIDs getAllocatedDeviceIDs() {
        return allocatedDeviceIDs;
    }

    /**
     * Sets the value of the allocatedDeviceIDs property.
     * 
     * @param value
     *     allowed object is
     *     {@link NASubscriber.AllocatedDeviceIDs }
     *     
     */
    public void setAllocatedDeviceIDs(NASubscriber.AllocatedDeviceIDs value) {
        this.allocatedDeviceIDs = value;
    }

    /**
     * Gets the value of the subscriber property.
     * 
     * @return
     *     possible object is
     *     {@link GenericSubscriberInfo }
     *     
     */
    public GenericSubscriberInfo getSubscriber() {
        return subscriber;
    }

    /**
     * Sets the value of the subscriber property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericSubscriberInfo }
     *     
     */
    public void setSubscriber(GenericSubscriberInfo value) {
        this.subscriber = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="NADeviceId" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NADeviceId"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "naDeviceId"
    })
    public static class AllocatedDeviceIDs {

        @XmlElement(name = "NADeviceId")
        protected List<String> naDeviceId;

        /**
         * Gets the value of the naDeviceId property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the naDeviceId property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNADeviceId().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getNADeviceId() {
            if (naDeviceId == null) {
                naDeviceId = new ArrayList<String>();
            }
            return this.naDeviceId;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="NAServiceSubscription" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NAServiceSubscription"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "naServiceSubscription"
    })
    public static class NaSubscriptions {

        @XmlElement(name = "NAServiceSubscription")
        protected List<NAServiceSubscription> naServiceSubscription;

        /**
         * Gets the value of the naServiceSubscription property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the naServiceSubscription property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNAServiceSubscription().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link NAServiceSubscription }
         * 
         * 
         */
        public List<NAServiceSubscription> getNAServiceSubscription() {
            if (naServiceSubscription == null) {
                naServiceSubscription = new ArrayList<NAServiceSubscription>();
            }
            return this.naServiceSubscription;
        }

    }

}
