//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.14 at 10:55:58 AM BST 
//


package org.etsi.uri._02657.v1_1_1_.retaineddata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import org.etsi.uri._02657.v1_3_1_1.retaineddata.DisclosureOwnershipRequest;


/**
 * <p>Java class for NationalRequestParameters complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NationalRequestParameters">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="countryCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="requestAuthorisation" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}RequestAuthorisation" minOccurs="0"/>
 *         &lt;element name="additionalParameters" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}AdditionalParameters" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/02657/v1.3.1#1/RetainedData}disclosureOwnershipRequest" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NationalRequestParameters", propOrder = {
    "countryCode",
    "requestAuthorisation",
    "additionalParameters",
    "disclosureOwnershipRequest"
})
public class NationalRequestParameters {

    @XmlElement(required = true)
    protected String countryCode;
    protected RequestAuthorisation requestAuthorisation;
    protected AdditionalParameters additionalParameters;
    @XmlElement(namespace = "http://uri.etsi.org/02657/v1.3.1#1/RetainedData")
    protected DisclosureOwnershipRequest disclosureOwnershipRequest;

    /**
     * Gets the value of the countryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * Sets the value of the countryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryCode(String value) {
        this.countryCode = value;
    }

    /**
     * Gets the value of the requestAuthorisation property.
     * 
     * @return
     *     possible object is
     *     {@link RequestAuthorisation }
     *     
     */
    public RequestAuthorisation getRequestAuthorisation() {
        return requestAuthorisation;
    }

    /**
     * Sets the value of the requestAuthorisation property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestAuthorisation }
     *     
     */
    public void setRequestAuthorisation(RequestAuthorisation value) {
        this.requestAuthorisation = value;
    }

    /**
     * Gets the value of the additionalParameters property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalParameters }
     *     
     */
    public AdditionalParameters getAdditionalParameters() {
        return additionalParameters;
    }

    /**
     * Sets the value of the additionalParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalParameters }
     *     
     */
    public void setAdditionalParameters(AdditionalParameters value) {
        this.additionalParameters = value;
    }

    /**
     * Gets the value of the disclosureOwnershipRequest property.
     * 
     * @return
     *     possible object is
     *     {@link DisclosureOwnershipRequest }
     *     
     */
    public DisclosureOwnershipRequest getDisclosureOwnershipRequest() {
        return disclosureOwnershipRequest;
    }

    /**
     * Sets the value of the disclosureOwnershipRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisclosureOwnershipRequest }
     *     
     */
    public void setDisclosureOwnershipRequest(DisclosureOwnershipRequest value) {
        this.disclosureOwnershipRequest = value;
    }

}
