//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.14 at 10:55:58 AM BST 
//


package org.etsi.uri._02657.v1_1_1_.retaineddata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NetworkAccessRecord complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NetworkAccessRecord">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="naSubscriber" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NASubscriber"/>
 *         &lt;element name="naServiceUsage" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NAServiceUsage"/>
 *         &lt;element name="naDevice" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NADevice"/>
 *         &lt;element name="naNetworkElement" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NANwElement"/>
 *         &lt;element name="naBillingDetails" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NABillingDetails"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NetworkAccessRecord", propOrder = {
    "naSubscriber",
    "naServiceUsage",
    "naDevice",
    "naNetworkElement",
    "naBillingDetails"
})
public class NetworkAccessRecord {

    protected NASubscriber naSubscriber;
    protected NAServiceUsage naServiceUsage;
    protected NADevice naDevice;
    protected NANwElement naNetworkElement;
    protected NABillingDetails naBillingDetails;

    /**
     * Gets the value of the naSubscriber property.
     * 
     * @return
     *     possible object is
     *     {@link NASubscriber }
     *     
     */
    public NASubscriber getNaSubscriber() {
        return naSubscriber;
    }

    /**
     * Sets the value of the naSubscriber property.
     * 
     * @param value
     *     allowed object is
     *     {@link NASubscriber }
     *     
     */
    public void setNaSubscriber(NASubscriber value) {
        this.naSubscriber = value;
    }

    /**
     * Gets the value of the naServiceUsage property.
     * 
     * @return
     *     possible object is
     *     {@link NAServiceUsage }
     *     
     */
    public NAServiceUsage getNaServiceUsage() {
        return naServiceUsage;
    }

    /**
     * Sets the value of the naServiceUsage property.
     * 
     * @param value
     *     allowed object is
     *     {@link NAServiceUsage }
     *     
     */
    public void setNaServiceUsage(NAServiceUsage value) {
        this.naServiceUsage = value;
    }

    /**
     * Gets the value of the naDevice property.
     * 
     * @return
     *     possible object is
     *     {@link NADevice }
     *     
     */
    public NADevice getNaDevice() {
        return naDevice;
    }

    /**
     * Sets the value of the naDevice property.
     * 
     * @param value
     *     allowed object is
     *     {@link NADevice }
     *     
     */
    public void setNaDevice(NADevice value) {
        this.naDevice = value;
    }

    /**
     * Gets the value of the naNetworkElement property.
     * 
     * @return
     *     possible object is
     *     {@link NANwElement }
     *     
     */
    public NANwElement getNaNetworkElement() {
        return naNetworkElement;
    }

    /**
     * Sets the value of the naNetworkElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link NANwElement }
     *     
     */
    public void setNaNetworkElement(NANwElement value) {
        this.naNetworkElement = value;
    }

    /**
     * Gets the value of the naBillingDetails property.
     * 
     * @return
     *     possible object is
     *     {@link NABillingDetails }
     *     
     */
    public NABillingDetails getNaBillingDetails() {
        return naBillingDetails;
    }

    /**
     * Sets the value of the naBillingDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link NABillingDetails }
     *     
     */
    public void setNaBillingDetails(NABillingDetails value) {
        this.naBillingDetails = value;
    }

}
