//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.14 at 10:55:58 AM BST 
//


package org.etsi.uri._02657.v1_1_1_.retaineddata;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.etsi.uri._02657.v1_1_1_.retaineddata package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _NationalResponsePayload_QNAME = new QName("http://uri.etsi.org/02657/v1.1.1#/RetainedData", "nationalResponsePayload");
    private final static QName _RetainedDataMessage_QNAME = new QName("http://uri.etsi.org/02657/v1.1.1#/RetainedData", "retainedDataMessage");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.etsi.uri._02657.v1_1_1_.retaineddata
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddressInformation }
     * 
     */
    public AddressInformation createAddressInformation() {
        return new AddressInformation();
    }

    /**
     * Create an instance of {@link MsgSubscriber }
     * 
     */
    public MsgSubscriber createMsgSubscriber() {
        return new MsgSubscriber();
    }

    /**
     * Create an instance of {@link NADevice }
     * 
     */
    public NADevice createNADevice() {
        return new NADevice();
    }

    /**
     * Create an instance of {@link ContactDetails }
     * 
     */
    public ContactDetails createContactDetails() {
        return new ContactDetails();
    }

    /**
     * Create an instance of {@link MsgTransmission }
     * 
     */
    public MsgTransmission createMsgTransmission() {
        return new MsgTransmission();
    }

    /**
     * Create an instance of {@link NAServiceUsage.NaStatus }
     * 
     */
    public NAServiceUsage.NaStatus createNAServiceUsageNaStatus() {
        return new NAServiceUsage.NaStatus();
    }

    /**
     * Create an instance of {@link NAServiceSubscription }
     * 
     */
    public NAServiceSubscription createNAServiceSubscription() {
        return new NAServiceSubscription();
    }

    /**
     * Create an instance of {@link MsgStoreOperation.Protocol }
     * 
     */
    public MsgStoreOperation.Protocol createMsgStoreOperationProtocol() {
        return new MsgStoreOperation.Protocol();
    }

    /**
     * Create an instance of {@link ContactDetails.ContactNumber }
     * 
     */
    public ContactDetails.ContactNumber createContactDetailsContactNumber() {
        return new ContactDetails.ContactNumber();
    }

    /**
     * Create an instance of {@link RipaAuthorisation }
     * 
     */
    public RipaAuthorisation createRipaAuthorisation() {
        return new RipaAuthorisation();
    }

    /**
     * Create an instance of {@link StatusMessage }
     * 
     */
    public StatusMessage createStatusMessage() {
        return new StatusMessage();
    }

    /**
     * Create an instance of {@link MsgServiceUsage }
     * 
     */
    public MsgServiceUsage createMsgServiceUsage() {
        return new MsgServiceUsage();
    }

    /**
     * Create an instance of {@link AuthenticationInfo }
     * 
     */
    public AuthenticationInfo createAuthenticationInfo() {
        return new AuthenticationInfo();
    }

    /**
     * Create an instance of {@link PrepayServiceEventType }
     * 
     */
    public PrepayServiceEventType createPrepayServiceEventType() {
        return new PrepayServiceEventType();
    }

    /**
     * Create an instance of {@link IndividualInfo.Gender }
     * 
     */
    public IndividualInfo.Gender createIndividualInfoGender() {
        return new IndividualInfo.Gender();
    }

    /**
     * Create an instance of {@link GAPolygonElements }
     * 
     */
    public GAPolygonElements createGAPolygonElements() {
        return new GAPolygonElements();
    }

    /**
     * Create an instance of {@link TelephonyCommunicationType }
     * 
     */
    public TelephonyCommunicationType createTelephonyCommunicationType() {
        return new TelephonyCommunicationType();
    }

    /**
     * Create an instance of {@link NationalResponsePayload }
     * 
     */
    public NationalResponsePayload createNationalResponsePayload() {
        return new NationalResponsePayload();
    }

    /**
     * Create an instance of {@link CancelAcknowledgement }
     * 
     */
    public CancelAcknowledgement createCancelAcknowledgement() {
        return new CancelAcknowledgement();
    }

    /**
     * Create an instance of {@link AdditionalInformation }
     * 
     */
    public AdditionalInformation createAdditionalInformation() {
        return new AdditionalInformation();
    }

    /**
     * Create an instance of {@link GetResultsMessage }
     * 
     */
    public GetResultsMessage createGetResultsMessage() {
        return new GetResultsMessage();
    }

    /**
     * Create an instance of {@link GAPolygon }
     * 
     */
    public GAPolygon createGAPolygon() {
        return new GAPolygon();
    }

    /**
     * Create an instance of {@link GprsInformation.SgsnAddress }
     * 
     */
    public GprsInformation.SgsnAddress createGprsInformationSgsnAddress() {
        return new GprsInformation.SgsnAddress();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link TelephonySubscriber.SubscribedTelephonyServices }
     * 
     */
    public TelephonySubscriber.SubscribedTelephonyServices createTelephonySubscriberSubscribedTelephonyServices() {
        return new TelephonySubscriber.SubscribedTelephonyServices();
    }

    /**
     * Create an instance of {@link TelephonyEventType }
     * 
     */
    public TelephonyEventType createTelephonyEventType() {
        return new TelephonyEventType();
    }

    /**
     * Create an instance of {@link NANwElement.SupportedAccessTypes }
     * 
     */
    public NANwElement.SupportedAccessTypes createNANwElementSupportedAccessTypes() {
        return new NANwElement.SupportedAccessTypes();
    }

    /**
     * Create an instance of {@link MsgTransmission.Protocol }
     * 
     */
    public MsgTransmission.Protocol createMsgTransmissionProtocol() {
        return new MsgTransmission.Protocol();
    }

    /**
     * Create an instance of {@link org.etsi.uri._02657.v1_1_1_.retaineddata.SubscribedTelephonyServices.RegisteredNumbers }
     * 
     */
    public org.etsi.uri._02657.v1_1_1_.retaineddata.SubscribedTelephonyServices.RegisteredNumbers createSubscribedTelephonyServicesRegisteredNumbers() {
        return new org.etsi.uri._02657.v1_1_1_.retaineddata.SubscribedTelephonyServices.RegisteredNumbers();
    }

    /**
     * Create an instance of {@link NABillingDetails.BillingRecords }
     * 
     */
    public NABillingDetails.BillingRecords createNABillingDetailsBillingRecords() {
        return new NABillingDetails.BillingRecords();
    }

    /**
     * Create an instance of {@link RetainedDataPayload }
     * 
     */
    public RetainedDataPayload createRetainedDataPayload() {
        return new RetainedDataPayload();
    }

    /**
     * Create an instance of {@link TimeSpan }
     * 
     */
    public TimeSpan createTimeSpan() {
        return new TimeSpan();
    }

    /**
     * Create an instance of {@link RequestConstraints.IsAMemberOf }
     * 
     */
    public RequestConstraints.IsAMemberOf createRequestConstraintsIsAMemberOf() {
        return new RequestConstraints.IsAMemberOf();
    }

    /**
     * Create an instance of {@link IPRange }
     * 
     */
    public IPRange createIPRange() {
        return new IPRange();
    }

    /**
     * Create an instance of {@link org.etsi.uri._02657.v1_1_1_.retaineddata.StatusResponse }
     * 
     */
    public org.etsi.uri._02657.v1_1_1_.retaineddata.StatusResponse createStatusResponse() {
        return new org.etsi.uri._02657.v1_1_1_.retaineddata.StatusResponse();
    }

    /**
     * Create an instance of {@link FurtherInformation }
     * 
     */
    public FurtherInformation createFurtherInformation() {
        return new FurtherInformation();
    }

    /**
     * Create an instance of {@link CancelMessage }
     * 
     */
    public CancelMessage createCancelMessage() {
        return new CancelMessage();
    }

    /**
     * Create an instance of {@link RetainedDataMessage }
     * 
     */
    public RetainedDataMessage createRetainedDataMessage() {
        return new RetainedDataMessage();
    }

    /**
     * Create an instance of {@link StatusMessage.StatusResponse }
     * 
     */
    public StatusMessage.StatusResponse createStatusMessageStatusResponse() {
        return new StatusMessage.StatusResponse();
    }

    /**
     * Create an instance of {@link TelephonyServiceType }
     * 
     */
    public TelephonyServiceType createTelephonyServiceType() {
        return new TelephonyServiceType();
    }

    /**
     * Create an instance of {@link RipaPurposeCode }
     * 
     */
    public RipaPurposeCode createRipaPurposeCode() {
        return new RipaPurposeCode();
    }

    /**
     * Create an instance of {@link MsgStore }
     * 
     */
    public MsgStore createMsgStore() {
        return new MsgStore();
    }

    /**
     * Create an instance of {@link DialUpInformation }
     * 
     */
    public DialUpInformation createDialUpInformation() {
        return new DialUpInformation();
    }

    /**
     * Create an instance of {@link PDFCopyInformation }
     * 
     */
    public PDFCopyInformation createPDFCopyInformation() {
        return new PDFCopyInformation();
    }

    /**
     * Create an instance of {@link NAAssignedAddress }
     * 
     */
    public NAAssignedAddress createNAAssignedAddress() {
        return new NAAssignedAddress();
    }

    /**
     * Create an instance of {@link TelephonySubscriber }
     * 
     */
    public TelephonySubscriber createTelephonySubscriber() {
        return new TelephonySubscriber();
    }

    /**
     * Create an instance of {@link MsgStoreOperation }
     * 
     */
    public MsgStoreOperation createMsgStoreOperation() {
        return new MsgStoreOperation();
    }

    /**
     * Create an instance of {@link GenericSubscriberInfo }
     * 
     */
    public GenericSubscriberInfo createGenericSubscriberInfo() {
        return new GenericSubscriberInfo();
    }

    /**
     * Create an instance of {@link GeographicalCoordinates.LatitudeSign }
     * 
     */
    public GeographicalCoordinates.LatitudeSign createGeographicalCoordinatesLatitudeSign() {
        return new GeographicalCoordinates.LatitudeSign();
    }

    /**
     * Create an instance of {@link ResponseRecord }
     * 
     */
    public ResponseRecord createResponseRecord() {
        return new ResponseRecord();
    }

    /**
     * Create an instance of {@link RequestAcknowledgement }
     * 
     */
    public RequestAcknowledgement createRequestAcknowledgement() {
        return new RequestAcknowledgement();
    }

    /**
     * Create an instance of {@link TelephonyBillingDetails }
     * 
     */
    public TelephonyBillingDetails createTelephonyBillingDetails() {
        return new TelephonyBillingDetails();
    }

    /**
     * Create an instance of {@link RequestStatus }
     * 
     */
    public RequestStatus createRequestStatus() {
        return new RequestStatus();
    }

    /**
     * Create an instance of {@link NAServiceUsage.NaAssignedAddress }
     * 
     */
    public NAServiceUsage.NaAssignedAddress createNAServiceUsageNaAssignedAddress() {
        return new NAServiceUsage.NaAssignedAddress();
    }

    /**
     * Create an instance of {@link PersonName }
     * 
     */
    public PersonName createPersonName() {
        return new PersonName();
    }

    /**
     * Create an instance of {@link ResponseStatus }
     * 
     */
    public ResponseStatus createResponseStatus() {
        return new ResponseStatus();
    }

    /**
     * Create an instance of {@link MsgStoreOperation.Operation }
     * 
     */
    public MsgStoreOperation.Operation createMsgStoreOperationOperation() {
        return new MsgStoreOperation.Operation();
    }

    /**
     * Create an instance of {@link IPAddress }
     * 
     */
    public IPAddress createIPAddress() {
        return new IPAddress();
    }

    /**
     * Create an instance of {@link RequestMessage }
     * 
     */
    public RequestMessage createRequestMessage() {
        return new RequestMessage();
    }

    /**
     * Create an instance of {@link NetworkAccessRecord }
     * 
     */
    public NetworkAccessRecord createNetworkAccessRecord() {
        return new NetworkAccessRecord();
    }

    /**
     * Create an instance of {@link NwAccessType }
     * 
     */
    public NwAccessType createNwAccessType() {
        return new NwAccessType();
    }

    /**
     * Create an instance of {@link GetStatusMessage }
     * 
     */
    public GetStatusMessage createGetStatusMessage() {
        return new GetStatusMessage();
    }

    /**
     * Create an instance of {@link MapDatum }
     * 
     */
    public MapDatum createMapDatum() {
        return new MapDatum();
    }

    /**
     * Create an instance of {@link NationalRequestParameters }
     * 
     */
    public NationalRequestParameters createNationalRequestParameters() {
        return new NationalRequestParameters();
    }

    /**
     * Create an instance of {@link IPAddressSetOrRangeOrMask }
     * 
     */
    public IPAddressSetOrRangeOrMask createIPAddressSetOrRangeOrMask() {
        return new IPAddressSetOrRangeOrMask();
    }

    /**
     * Create an instance of {@link NASubscriber.AllocatedDeviceIDs }
     * 
     */
    public NASubscriber.AllocatedDeviceIDs createNASubscriberAllocatedDeviceIDs() {
        return new NASubscriber.AllocatedDeviceIDs();
    }

    /**
     * Create an instance of {@link TelephonyRecord }
     * 
     */
    public TelephonyRecord createTelephonyRecord() {
        return new TelephonyRecord();
    }

    /**
     * Create an instance of {@link SmsInformation.SmsEvent }
     * 
     */
    public SmsInformation.SmsEvent createSmsInformationSmsEvent() {
        return new SmsInformation.SmsEvent();
    }

    /**
     * Create an instance of {@link ResponseMessage.ResponsePayload }
     * 
     */
    public ResponseMessage.ResponsePayload createResponseMessageResponsePayload() {
        return new ResponseMessage.ResponsePayload();
    }

    /**
     * Create an instance of {@link org.etsi.uri._02657.v1_1_1_.retaineddata.BillingRecords }
     * 
     */
    public org.etsi.uri._02657.v1_1_1_.retaineddata.BillingRecords createBillingRecords() {
        return new org.etsi.uri._02657.v1_1_1_.retaineddata.BillingRecords();
    }

    /**
     * Create an instance of {@link MessagingEventType }
     * 
     */
    public MessagingEventType createMessagingEventType() {
        return new MessagingEventType();
    }

    /**
     * Create an instance of {@link TelephonyNetworkElement }
     * 
     */
    public TelephonyNetworkElement createTelephonyNetworkElement() {
        return new TelephonyNetworkElement();
    }

    /**
     * Create an instance of {@link MsgTransmission.DeliveryStatus }
     * 
     */
    public MsgTransmission.DeliveryStatus createMsgTransmissionDeliveryStatus() {
        return new MsgTransmission.DeliveryStatus();
    }

    /**
     * Create an instance of {@link NASubscriber }
     * 
     */
    public NASubscriber createNASubscriber() {
        return new NASubscriber();
    }

    /**
     * Create an instance of {@link SmsInformation.SmsType }
     * 
     */
    public SmsInformation.SmsType createSmsInformationSmsType() {
        return new SmsInformation.SmsType();
    }

    /**
     * Create an instance of {@link TelephonyBearerService }
     * 
     */
    public TelephonyBearerService createTelephonyBearerService() {
        return new TelephonyBearerService();
    }

    /**
     * Create an instance of {@link TelephonyPartyRole }
     * 
     */
    public TelephonyPartyRole createTelephonyPartyRole() {
        return new TelephonyPartyRole();
    }

    /**
     * Create an instance of {@link TelephonySubscriberInfo }
     * 
     */
    public TelephonySubscriberInfo createTelephonySubscriberInfo() {
        return new TelephonySubscriberInfo();
    }

    /**
     * Create an instance of {@link TelephonyDevice }
     * 
     */
    public TelephonyDevice createTelephonyDevice() {
        return new TelephonyDevice();
    }

    /**
     * Create an instance of {@link TelephonyServiceUsage.EventInformation }
     * 
     */
    public TelephonyServiceUsage.EventInformation createTelephonyServiceUsageEventInformation() {
        return new TelephonyServiceUsage.EventInformation();
    }

    /**
     * Create an instance of {@link MessageRecord }
     * 
     */
    public MessageRecord createMessageRecord() {
        return new MessageRecord();
    }

    /**
     * Create an instance of {@link org.etsi.uri._02657.v1_1_1_.retaineddata.SubscribedTelephonyServices }
     * 
     */
    public org.etsi.uri._02657.v1_1_1_.retaineddata.SubscribedTelephonyServices createSubscribedTelephonyServices() {
        return new org.etsi.uri._02657.v1_1_1_.retaineddata.SubscribedTelephonyServices();
    }

    /**
     * Create an instance of {@link RetainedDataHeader }
     * 
     */
    public RetainedDataHeader createRetainedDataHeader() {
        return new RetainedDataHeader();
    }

    /**
     * Create an instance of {@link NABillingDetails }
     * 
     */
    public NABillingDetails createNABillingDetails() {
        return new NABillingDetails();
    }

    /**
     * Create an instance of {@link NANwElement }
     * 
     */
    public NANwElement createNANwElement() {
        return new NANwElement();
    }

    /**
     * Create an instance of {@link TelephonyEventInformation }
     * 
     */
    public TelephonyEventInformation createTelephonyEventInformation() {
        return new TelephonyEventInformation();
    }

    /**
     * Create an instance of {@link ExemptionExpiry }
     * 
     */
    public ExemptionExpiry createExemptionExpiry() {
        return new ExemptionExpiry();
    }

    /**
     * Create an instance of {@link RequestAuthorisation }
     * 
     */
    public RequestAuthorisation createRequestAuthorisation() {
        return new RequestAuthorisation();
    }

    /**
     * Create an instance of {@link CallForwardingEventType }
     * 
     */
    public CallForwardingEventType createCallForwardingEventType() {
        return new CallForwardingEventType();
    }

    /**
     * Create an instance of {@link TelephonyPartyInformation }
     * 
     */
    public TelephonyPartyInformation createTelephonyPartyInformation() {
        return new TelephonyPartyInformation();
    }

    /**
     * Create an instance of {@link GetStatusMessage.RequestNumbers }
     * 
     */
    public GetStatusMessage.RequestNumbers createGetStatusMessageRequestNumbers() {
        return new GetStatusMessage.RequestNumbers();
    }

    /**
     * Create an instance of {@link TelephonyLocation }
     * 
     */
    public TelephonyLocation createTelephonyLocation() {
        return new TelephonyLocation();
    }

    /**
     * Create an instance of {@link CallConferenceEventType }
     * 
     */
    public CallConferenceEventType createCallConferenceEventType() {
        return new CallConferenceEventType();
    }

    /**
     * Create an instance of {@link RetainedDataRecord }
     * 
     */
    public RetainedDataRecord createRetainedDataRecord() {
        return new RetainedDataRecord();
    }

    /**
     * Create an instance of {@link SmsInformation }
     * 
     */
    public SmsInformation createSmsInformation() {
        return new SmsInformation();
    }

    /**
     * Create an instance of {@link AdditionalParameters }
     * 
     */
    public AdditionalParameters createAdditionalParameters() {
        return new AdditionalParameters();
    }

    /**
     * Create an instance of {@link TelephonyServiceUsage }
     * 
     */
    public TelephonyServiceUsage createTelephonyServiceUsage() {
        return new TelephonyServiceUsage();
    }

    /**
     * Create an instance of {@link GSMLocation }
     * 
     */
    public GSMLocation createGSMLocation() {
        return new GSMLocation();
    }

    /**
     * Create an instance of {@link RequestConstraints }
     * 
     */
    public RequestConstraints createRequestConstraints() {
        return new RequestConstraints();
    }

    /**
     * Create an instance of {@link TelephonyServiceUsage.PartyInformation }
     * 
     */
    public TelephonyServiceUsage.PartyInformation createTelephonyServiceUsagePartyInformation() {
        return new TelephonyServiceUsage.PartyInformation();
    }

    /**
     * Create an instance of {@link GAPointWithUnCertainty }
     * 
     */
    public GAPointWithUnCertainty createGAPointWithUnCertainty() {
        return new GAPointWithUnCertainty();
    }

    /**
     * Create an instance of {@link NAServiceUsage }
     * 
     */
    public NAServiceUsage createNAServiceUsage() {
        return new NAServiceUsage();
    }

    /**
     * Create an instance of {@link NationalRecordPayload }
     * 
     */
    public NationalRecordPayload createNationalRecordPayload() {
        return new NationalRecordPayload();
    }

    /**
     * Create an instance of {@link MsgSubscriber.MsgStores }
     * 
     */
    public MsgSubscriber.MsgStores createMsgSubscriberMsgStores() {
        return new MsgSubscriber.MsgStores();
    }

    /**
     * Create an instance of {@link IPMask }
     * 
     */
    public IPMask createIPMask() {
        return new IPMask();
    }

    /**
     * Create an instance of {@link GSMLocation.UtmRefCoordinates }
     * 
     */
    public GSMLocation.UtmRefCoordinates createGSMLocationUtmRefCoordinates() {
        return new GSMLocation.UtmRefCoordinates();
    }

    /**
     * Create an instance of {@link TelephonyDevice.DeviceIDType }
     * 
     */
    public TelephonyDevice.DeviceIDType createTelephonyDeviceDeviceIDType() {
        return new TelephonyDevice.DeviceIDType();
    }

    /**
     * Create an instance of {@link DSARExemption }
     * 
     */
    public DSARExemption createDSARExemption() {
        return new DSARExemption();
    }

    /**
     * Create an instance of {@link RequiredByDetails }
     * 
     */
    public RequiredByDetails createRequiredByDetails() {
        return new RequiredByDetails();
    }

    /**
     * Create an instance of {@link GAPoint }
     * 
     */
    public GAPoint createGAPoint() {
        return new GAPoint();
    }

    /**
     * Create an instance of {@link BasicEventType }
     * 
     */
    public BasicEventType createBasicEventType() {
        return new BasicEventType();
    }

    /**
     * Create an instance of {@link RequiredByReason }
     * 
     */
    public RequiredByReason createRequiredByReason() {
        return new RequiredByReason();
    }

    /**
     * Create an instance of {@link UMTSLocation }
     * 
     */
    public UMTSLocation createUMTSLocation() {
        return new UMTSLocation();
    }

    /**
     * Create an instance of {@link GSMLocation.UtmCoordinates }
     * 
     */
    public GSMLocation.UtmCoordinates createGSMLocationUtmCoordinates() {
        return new GSMLocation.UtmCoordinates();
    }

    /**
     * Create an instance of {@link ResponseMessage }
     * 
     */
    public ResponseMessage createResponseMessage() {
        return new ResponseMessage();
    }

    /**
     * Create an instance of {@link NAAssignedAddress.AddressType }
     * 
     */
    public NAAssignedAddress.AddressType createNAAssignedAddressAddressType() {
        return new NAAssignedAddress.AddressType();
    }

    /**
     * Create an instance of {@link IndividualInfo }
     * 
     */
    public IndividualInfo createIndividualInfo() {
        return new IndividualInfo();
    }

    /**
     * Create an instance of {@link SmsInformation.SmsStatus }
     * 
     */
    public SmsInformation.SmsStatus createSmsInformationSmsStatus() {
        return new SmsInformation.SmsStatus();
    }

    /**
     * Create an instance of {@link RequiredByLegislation }
     * 
     */
    public RequiredByLegislation createRequiredByLegislation() {
        return new RequiredByLegislation();
    }

    /**
     * Create an instance of {@link GSMLocation.GeoCoordinates }
     * 
     */
    public GSMLocation.GeoCoordinates createGSMLocationGeoCoordinates() {
        return new GSMLocation.GeoCoordinates();
    }

    /**
     * Create an instance of {@link NASubscriber.NaSubscriptions }
     * 
     */
    public NASubscriber.NaSubscriptions createNASubscriberNaSubscriptions() {
        return new NASubscriber.NaSubscriptions();
    }

    /**
     * Create an instance of {@link IPAddressSetOrRangeOrMask.Set }
     * 
     */
    public IPAddressSetOrRangeOrMask.Set createIPAddressSetOrRangeOrMaskSet() {
        return new IPAddressSetOrRangeOrMask.Set();
    }

    /**
     * Create an instance of {@link RequestID }
     * 
     */
    public RequestID createRequestID() {
        return new RequestID();
    }

    /**
     * Create an instance of {@link TelephonyBillingDetails.BillingRecords }
     * 
     */
    public TelephonyBillingDetails.BillingRecords createTelephonyBillingDetailsBillingRecords() {
        return new TelephonyBillingDetails.BillingRecords();
    }

    /**
     * Create an instance of {@link GprsInformation }
     * 
     */
    public GprsInformation createGprsInformation() {
        return new GprsInformation();
    }

    /**
     * Create an instance of {@link NULL }
     * 
     */
    public NULL createNULL() {
        return new NULL();
    }

    /**
     * Create an instance of {@link ResponseAcknowledgement }
     * 
     */
    public ResponseAcknowledgement createResponseAcknowledgement() {
        return new ResponseAcknowledgement();
    }

    /**
     * Create an instance of {@link OrganizationInfo }
     * 
     */
    public OrganizationInfo createOrganizationInfo() {
        return new OrganizationInfo();
    }

    /**
     * Create an instance of {@link TelephonyPartyInformation.Locations }
     * 
     */
    public TelephonyPartyInformation.Locations createTelephonyPartyInformationLocations() {
        return new TelephonyPartyInformation.Locations();
    }

    /**
     * Create an instance of {@link GeographicalCoordinates }
     * 
     */
    public GeographicalCoordinates createGeographicalCoordinates() {
        return new GeographicalCoordinates();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NationalResponsePayload }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/02657/v1.1.1#/RetainedData", name = "nationalResponsePayload")
    public JAXBElement<NationalResponsePayload> createNationalResponsePayload(NationalResponsePayload value) {
        return new JAXBElement<NationalResponsePayload>(_NationalResponsePayload_QNAME, NationalResponsePayload.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RetainedDataMessage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/02657/v1.1.1#/RetainedData", name = "retainedDataMessage")
    public JAXBElement<RetainedDataMessage> createRetainedDataMessage(RetainedDataMessage value) {
        return new JAXBElement<RetainedDataMessage>(_RetainedDataMessage_QNAME, RetainedDataMessage.class, null, value);
    }

}
