//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.14 at 10:55:58 AM BST 
//


package org.etsi.uri._02657.v1_1_1_.retaineddata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RequestAuthorisation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RequestAuthorisation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="ripaAuthorisation" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}RipaAuthorisation"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestAuthorisation", propOrder = {
    "ripaAuthorisation"
})
public class RequestAuthorisation {

    protected RipaAuthorisation ripaAuthorisation;

    /**
     * Gets the value of the ripaAuthorisation property.
     * 
     * @return
     *     possible object is
     *     {@link RipaAuthorisation }
     *     
     */
    public RipaAuthorisation getRipaAuthorisation() {
        return ripaAuthorisation;
    }

    /**
     * Sets the value of the ripaAuthorisation property.
     * 
     * @param value
     *     allowed object is
     *     {@link RipaAuthorisation }
     *     
     */
    public void setRipaAuthorisation(RipaAuthorisation value) {
        this.ripaAuthorisation = value;
    }

}
