//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.14 at 10:55:58 AM BST 
//


package org.etsi.uri._02657.v1_1_1_.retaineddata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResponseAcknowledgement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResponseAcknowledgement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="acknowledgeCompleteResults" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL" minOccurs="0"/>
 *         &lt;element name="acknowledgePartialResults" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResponseAcknowledgement", propOrder = {
    "acknowledgeCompleteResults",
    "acknowledgePartialResults"
})
public class ResponseAcknowledgement {

    protected NULL acknowledgeCompleteResults;
    protected NULL acknowledgePartialResults;

    /**
     * Gets the value of the acknowledgeCompleteResults property.
     * 
     * @return
     *     possible object is
     *     {@link NULL }
     *     
     */
    public NULL getAcknowledgeCompleteResults() {
        return acknowledgeCompleteResults;
    }

    /**
     * Sets the value of the acknowledgeCompleteResults property.
     * 
     * @param value
     *     allowed object is
     *     {@link NULL }
     *     
     */
    public void setAcknowledgeCompleteResults(NULL value) {
        this.acknowledgeCompleteResults = value;
    }

    /**
     * Gets the value of the acknowledgePartialResults property.
     * 
     * @return
     *     possible object is
     *     {@link NULL }
     *     
     */
    public NULL getAcknowledgePartialResults() {
        return acknowledgePartialResults;
    }

    /**
     * Sets the value of the acknowledgePartialResults property.
     * 
     * @param value
     *     allowed object is
     *     {@link NULL }
     *     
     */
    public void setAcknowledgePartialResults(NULL value) {
        this.acknowledgePartialResults = value;
    }

}
