//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.14 at 10:55:58 AM BST 
//


package org.etsi.uri._02657.v1_1_1_.retaineddata;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResponseMessage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResponseMessage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="responseStatus" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}ResponseStatus"/>
 *         &lt;element name="responsePayload" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="ResponseRecord" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}ResponseRecord"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="nationalResponsePayload" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NationalResponsePayload" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResponseMessage", propOrder = {
    "responseStatus",
    "responsePayload",
    "nationalResponsePayload"
})
public class ResponseMessage {

    @XmlElement(required = true)
    protected ResponseStatus responseStatus;
    protected ResponseMessage.ResponsePayload responsePayload;
    protected NationalResponsePayload nationalResponsePayload;

    /**
     * Gets the value of the responseStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseStatus }
     *     
     */
    public ResponseStatus getResponseStatus() {
        return responseStatus;
    }

    /**
     * Sets the value of the responseStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseStatus }
     *     
     */
    public void setResponseStatus(ResponseStatus value) {
        this.responseStatus = value;
    }

    /**
     * Gets the value of the responsePayload property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseMessage.ResponsePayload }
     *     
     */
    public ResponseMessage.ResponsePayload getResponsePayload() {
        return responsePayload;
    }

    /**
     * Sets the value of the responsePayload property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseMessage.ResponsePayload }
     *     
     */
    public void setResponsePayload(ResponseMessage.ResponsePayload value) {
        this.responsePayload = value;
    }

    /**
     * Gets the value of the nationalResponsePayload property.
     * 
     * @return
     *     possible object is
     *     {@link NationalResponsePayload }
     *     
     */
    public NationalResponsePayload getNationalResponsePayload() {
        return nationalResponsePayload;
    }

    /**
     * Sets the value of the nationalResponsePayload property.
     * 
     * @param value
     *     allowed object is
     *     {@link NationalResponsePayload }
     *     
     */
    public void setNationalResponsePayload(NationalResponsePayload value) {
        this.nationalResponsePayload = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="ResponseRecord" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}ResponseRecord"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "responseRecord"
    })
    public static class ResponsePayload {

        @XmlElement(name = "ResponseRecord")
        protected List<ResponseRecord> responseRecord;

        /**
         * Gets the value of the responseRecord property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the responseRecord property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getResponseRecord().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ResponseRecord }
         * 
         * 
         */
        public List<ResponseRecord> getResponseRecord() {
            if (responseRecord == null) {
                responseRecord = new ArrayList<ResponseRecord>();
            }
            return this.responseRecord;
        }

    }

}
