//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.14 at 10:55:58 AM BST 
//


package org.etsi.uri._02657.v1_1_1_.retaineddata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RetainedDataHeader complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RetainedDataHeader">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="requestID" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}RequestID"/>
 *         &lt;element name="cSPID" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}CSPID"/>
 *         &lt;element name="timeStamp" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}GeneralizedTime"/>
 *         &lt;element name="thirdPartyCSPID" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}CSPID" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RetainedDataHeader", propOrder = {
    "requestID",
    "cspid",
    "timeStamp",
    "thirdPartyCSPID"
})
public class RetainedDataHeader {

    @XmlElement(required = true)
    protected RequestID requestID;
    @XmlElement(name = "cSPID", required = true)
    protected String cspid;
    @XmlElement(required = true)
    protected String timeStamp;
    protected String thirdPartyCSPID;

    /**
     * Gets the value of the requestID property.
     * 
     * @return
     *     possible object is
     *     {@link RequestID }
     *     
     */
    public RequestID getRequestID() {
        return requestID;
    }

    /**
     * Sets the value of the requestID property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestID }
     *     
     */
    public void setRequestID(RequestID value) {
        this.requestID = value;
    }

    /**
     * Gets the value of the cspid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCSPID() {
        return cspid;
    }

    /**
     * Sets the value of the cspid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCSPID(String value) {
        this.cspid = value;
    }

    /**
     * Gets the value of the timeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeStamp() {
        return timeStamp;
    }

    /**
     * Sets the value of the timeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeStamp(String value) {
        this.timeStamp = value;
    }

    /**
     * Gets the value of the thirdPartyCSPID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThirdPartyCSPID() {
        return thirdPartyCSPID;
    }

    /**
     * Sets the value of the thirdPartyCSPID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThirdPartyCSPID(String value) {
        this.thirdPartyCSPID = value;
    }

}
