//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.14 at 10:55:58 AM BST 
//


package org.etsi.uri._02657.v1_1_1_.retaineddata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RipaAuthorisation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RipaAuthorisation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="authorisationIdentifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="purposeCode" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}RipaPurposeCode"/>
 *         &lt;element name="authorisingOfficer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rank" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="startDate" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}GeneralizedTime"/>
 *         &lt;element name="expiryDate" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}GeneralizedTime" minOccurs="0"/>
 *         &lt;element name="operationReference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/02657/v1.3.1#1/RetainedData}spocIdentifier" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RipaAuthorisation", propOrder = {
    "authorisationIdentifier",
    "purposeCode",
    "authorisingOfficer",
    "rank",
    "startDate",
    "expiryDate",
    "operationReference",
    "spocIdentifier"
})
public class RipaAuthorisation {

    @XmlElement(required = true)
    protected String authorisationIdentifier;
    @XmlElement(required = true)
    protected RipaPurposeCode purposeCode;
    @XmlElement(required = true)
    protected String authorisingOfficer;
    @XmlElement(required = true)
    protected String rank;
    @XmlElement(required = true)
    protected String startDate;
    protected String expiryDate;
    protected String operationReference;
    @XmlElement(namespace = "http://uri.etsi.org/02657/v1.3.1#1/RetainedData")
    protected String spocIdentifier;

    /**
     * Gets the value of the authorisationIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorisationIdentifier() {
        return authorisationIdentifier;
    }

    /**
     * Sets the value of the authorisationIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorisationIdentifier(String value) {
        this.authorisationIdentifier = value;
    }

    /**
     * Gets the value of the purposeCode property.
     * 
     * @return
     *     possible object is
     *     {@link RipaPurposeCode }
     *     
     */
    public RipaPurposeCode getPurposeCode() {
        return purposeCode;
    }

    /**
     * Sets the value of the purposeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link RipaPurposeCode }
     *     
     */
    public void setPurposeCode(RipaPurposeCode value) {
        this.purposeCode = value;
    }

    /**
     * Gets the value of the authorisingOfficer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorisingOfficer() {
        return authorisingOfficer;
    }

    /**
     * Sets the value of the authorisingOfficer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorisingOfficer(String value) {
        this.authorisingOfficer = value;
    }

    /**
     * Gets the value of the rank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRank() {
        return rank;
    }

    /**
     * Sets the value of the rank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRank(String value) {
        this.rank = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartDate(String value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the expiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpiryDate() {
        return expiryDate;
    }

    /**
     * Sets the value of the expiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpiryDate(String value) {
        this.expiryDate = value;
    }

    /**
     * Gets the value of the operationReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperationReference() {
        return operationReference;
    }

    /**
     * Sets the value of the operationReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperationReference(String value) {
        this.operationReference = value;
    }

    /**
     * Gets the value of the spocIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpocIdentifier() {
        return spocIdentifier;
    }

    /**
     * Sets the value of the spocIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpocIdentifier(String value) {
        this.spocIdentifier = value;
    }

}
