//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.14 at 10:55:58 AM BST 
//


package org.etsi.uri._02657.v1_1_1_.retaineddata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RipaPurposeCode complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RipaPurposeCode">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="s22a" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *         &lt;element name="s22b" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *         &lt;element name="s22c" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *         &lt;element name="s22d" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *         &lt;element name="s22e" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *         &lt;element name="s22f" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *         &lt;element name="s22g" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *         &lt;element name="s22h" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *         &lt;element name="s22i" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *         &lt;element ref="{http://uri.etsi.org/02657/v1.3.1#1/RetainedData}si1878i"/>
 *         &lt;element ref="{http://uri.etsi.org/02657/v1.3.1#1/RetainedData}si1878bi"/>
 *         &lt;element ref="{http://uri.etsi.org/02657/v1.3.1#1/RetainedData}si1878bii"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RipaPurposeCode", propOrder = {
    "s22A",
    "s22B",
    "s22C",
    "s22D",
    "s22E",
    "s22F",
    "s22G",
    "s22H",
    "s22I",
    "si1878I",
    "si1878Bi",
    "si1878Bii"
})
public class RipaPurposeCode {

    @XmlElement(name = "s22a")
    protected NULL s22A;
    @XmlElement(name = "s22b")
    protected NULL s22B;
    @XmlElement(name = "s22c")
    protected NULL s22C;
    @XmlElement(name = "s22d")
    protected NULL s22D;
    @XmlElement(name = "s22e")
    protected NULL s22E;
    @XmlElement(name = "s22f")
    protected NULL s22F;
    @XmlElement(name = "s22g")
    protected NULL s22G;
    @XmlElement(name = "s22h")
    protected NULL s22H;
    @XmlElement(name = "s22i")
    protected NULL s22I;
    @XmlElement(name = "si1878i", namespace = "http://uri.etsi.org/02657/v1.3.1#1/RetainedData")
    protected NULL si1878I;
    @XmlElement(name = "si1878bi", namespace = "http://uri.etsi.org/02657/v1.3.1#1/RetainedData")
    protected NULL si1878Bi;
    @XmlElement(name = "si1878bii", namespace = "http://uri.etsi.org/02657/v1.3.1#1/RetainedData")
    protected NULL si1878Bii;

    /**
     * Gets the value of the s22A property.
     * 
     * @return
     *     possible object is
     *     {@link NULL }
     *     
     */
    public NULL getS22A() {
        return s22A;
    }

    /**
     * Sets the value of the s22A property.
     * 
     * @param value
     *     allowed object is
     *     {@link NULL }
     *     
     */
    public void setS22A(NULL value) {
        this.s22A = value;
    }

    /**
     * Gets the value of the s22B property.
     * 
     * @return
     *     possible object is
     *     {@link NULL }
     *     
     */
    public NULL getS22B() {
        return s22B;
    }

    /**
     * Sets the value of the s22B property.
     * 
     * @param value
     *     allowed object is
     *     {@link NULL }
     *     
     */
    public void setS22B(NULL value) {
        this.s22B = value;
    }

    /**
     * Gets the value of the s22C property.
     * 
     * @return
     *     possible object is
     *     {@link NULL }
     *     
     */
    public NULL getS22C() {
        return s22C;
    }

    /**
     * Sets the value of the s22C property.
     * 
     * @param value
     *     allowed object is
     *     {@link NULL }
     *     
     */
    public void setS22C(NULL value) {
        this.s22C = value;
    }

    /**
     * Gets the value of the s22D property.
     * 
     * @return
     *     possible object is
     *     {@link NULL }
     *     
     */
    public NULL getS22D() {
        return s22D;
    }

    /**
     * Sets the value of the s22D property.
     * 
     * @param value
     *     allowed object is
     *     {@link NULL }
     *     
     */
    public void setS22D(NULL value) {
        this.s22D = value;
    }

    /**
     * Gets the value of the s22E property.
     * 
     * @return
     *     possible object is
     *     {@link NULL }
     *     
     */
    public NULL getS22E() {
        return s22E;
    }

    /**
     * Sets the value of the s22E property.
     * 
     * @param value
     *     allowed object is
     *     {@link NULL }
     *     
     */
    public void setS22E(NULL value) {
        this.s22E = value;
    }

    /**
     * Gets the value of the s22F property.
     * 
     * @return
     *     possible object is
     *     {@link NULL }
     *     
     */
    public NULL getS22F() {
        return s22F;
    }

    /**
     * Sets the value of the s22F property.
     * 
     * @param value
     *     allowed object is
     *     {@link NULL }
     *     
     */
    public void setS22F(NULL value) {
        this.s22F = value;
    }

    /**
     * Gets the value of the s22G property.
     * 
     * @return
     *     possible object is
     *     {@link NULL }
     *     
     */
    public NULL getS22G() {
        return s22G;
    }

    /**
     * Sets the value of the s22G property.
     * 
     * @param value
     *     allowed object is
     *     {@link NULL }
     *     
     */
    public void setS22G(NULL value) {
        this.s22G = value;
    }

    /**
     * Gets the value of the s22H property.
     * 
     * @return
     *     possible object is
     *     {@link NULL }
     *     
     */
    public NULL getS22H() {
        return s22H;
    }

    /**
     * Sets the value of the s22H property.
     * 
     * @param value
     *     allowed object is
     *     {@link NULL }
     *     
     */
    public void setS22H(NULL value) {
        this.s22H = value;
    }

    /**
     * Gets the value of the s22I property.
     * 
     * @return
     *     possible object is
     *     {@link NULL }
     *     
     */
    public NULL getS22I() {
        return s22I;
    }

    /**
     * Sets the value of the s22I property.
     * 
     * @param value
     *     allowed object is
     *     {@link NULL }
     *     
     */
    public void setS22I(NULL value) {
        this.s22I = value;
    }

    /**
     * Gets the value of the si1878I property.
     * 
     * @return
     *     possible object is
     *     {@link NULL }
     *     
     */
    public NULL getSi1878I() {
        return si1878I;
    }

    /**
     * Sets the value of the si1878I property.
     * 
     * @param value
     *     allowed object is
     *     {@link NULL }
     *     
     */
    public void setSi1878I(NULL value) {
        this.si1878I = value;
    }

    /**
     * Gets the value of the si1878Bi property.
     * 
     * @return
     *     possible object is
     *     {@link NULL }
     *     
     */
    public NULL getSi1878Bi() {
        return si1878Bi;
    }

    /**
     * Sets the value of the si1878Bi property.
     * 
     * @param value
     *     allowed object is
     *     {@link NULL }
     *     
     */
    public void setSi1878Bi(NULL value) {
        this.si1878Bi = value;
    }

    /**
     * Gets the value of the si1878Bii property.
     * 
     * @return
     *     possible object is
     *     {@link NULL }
     *     
     */
    public NULL getSi1878Bii() {
        return si1878Bii;
    }

    /**
     * Sets the value of the si1878Bii property.
     * 
     * @param value
     *     allowed object is
     *     {@link NULL }
     *     
     */
    public void setSi1878Bii(NULL value) {
        this.si1878Bii = value;
    }

}
