//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.14 at 10:55:58 AM BST 
//


package org.etsi.uri._02657.v1_1_1_.retaineddata;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import org.etsi.uri._02657.v1_3_1_1.retaineddata.AllocatedDeviceIDs;
import org.etsi.uri._02657.v1_3_1_1.retaineddata.IMEI;
import org.etsi.uri._02657.v1_3_1_1.retaineddata.NationalTelephonySubscriptionInfo;


/**
 * <p>Java class for SubscribedTelephonyServices complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubscribedTelephonyServices">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="serviceID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="providerID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="timeSpan" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}TimeSpan" minOccurs="0"/>
 *         &lt;element name="registeredNumbers" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="PartyNumber" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}PartyNumber"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="registeredICCID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="serviceType" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}TelephonyServiceType" minOccurs="0"/>
 *         &lt;element name="installationAddress" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}AddressInformation" minOccurs="0"/>
 *         &lt;element name="connectionDate" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}GeneralizedTime" minOccurs="0"/>
 *         &lt;element name="iMSI" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}IMSI" minOccurs="0"/>
 *         &lt;element name="carrierPreselect" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="lineStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/02657/v1.3.1#1/RetainedData}allocatedDeviceIDs" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/02657/v1.3.1#1/RetainedData}pUKCode" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/02657/v1.3.1#1/RetainedData}pUK2Code" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/02657/v1.3.1#1/RetainedData}iMEI" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/02657/v1.3.1#1/RetainedData}nationalTelephonySubscriptionInfo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubscribedTelephonyServices", propOrder = {
    "serviceID",
    "providerID",
    "timeSpan",
    "registeredNumbers",
    "registeredICCID",
    "serviceType",
    "installationAddress",
    "connectionDate",
    "imsi",
    "carrierPreselect",
    "lineStatus",
    "allocatedDeviceIDs",
    "pukCode",
    "puk2Code",
    "imei",
    "nationalTelephonySubscriptionInfo"
})
public class SubscribedTelephonyServices {

    protected String serviceID;
    protected String providerID;
    protected TimeSpan timeSpan;
    protected SubscribedTelephonyServices.RegisteredNumbers registeredNumbers;
    protected String registeredICCID;
    protected TelephonyServiceType serviceType;
    protected AddressInformation installationAddress;
    protected String connectionDate;
    @XmlElement(name = "iMSI", type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] imsi;
    protected Boolean carrierPreselect;
    protected String lineStatus;
    @XmlElement(namespace = "http://uri.etsi.org/02657/v1.3.1#1/RetainedData")
    protected AllocatedDeviceIDs allocatedDeviceIDs;
    @XmlElement(name = "pUKCode", namespace = "http://uri.etsi.org/02657/v1.3.1#1/RetainedData")
    protected String pukCode;
    @XmlElement(name = "pUK2Code", namespace = "http://uri.etsi.org/02657/v1.3.1#1/RetainedData")
    protected String puk2Code;
    @XmlElement(name = "iMEI", namespace = "http://uri.etsi.org/02657/v1.3.1#1/RetainedData")
    protected IMEI imei;
    @XmlElement(namespace = "http://uri.etsi.org/02657/v1.3.1#1/RetainedData")
    protected NationalTelephonySubscriptionInfo nationalTelephonySubscriptionInfo;

    /**
     * Gets the value of the serviceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceID() {
        return serviceID;
    }

    /**
     * Sets the value of the serviceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceID(String value) {
        this.serviceID = value;
    }

    /**
     * Gets the value of the providerID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderID() {
        return providerID;
    }

    /**
     * Sets the value of the providerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderID(String value) {
        this.providerID = value;
    }

    /**
     * Gets the value of the timeSpan property.
     * 
     * @return
     *     possible object is
     *     {@link TimeSpan }
     *     
     */
    public TimeSpan getTimeSpan() {
        return timeSpan;
    }

    /**
     * Sets the value of the timeSpan property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeSpan }
     *     
     */
    public void setTimeSpan(TimeSpan value) {
        this.timeSpan = value;
    }

    /**
     * Gets the value of the registeredNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link SubscribedTelephonyServices.RegisteredNumbers }
     *     
     */
    public SubscribedTelephonyServices.RegisteredNumbers getRegisteredNumbers() {
        return registeredNumbers;
    }

    /**
     * Sets the value of the registeredNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubscribedTelephonyServices.RegisteredNumbers }
     *     
     */
    public void setRegisteredNumbers(SubscribedTelephonyServices.RegisteredNumbers value) {
        this.registeredNumbers = value;
    }

    /**
     * Gets the value of the registeredICCID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegisteredICCID() {
        return registeredICCID;
    }

    /**
     * Sets the value of the registeredICCID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegisteredICCID(String value) {
        this.registeredICCID = value;
    }

    /**
     * Gets the value of the serviceType property.
     * 
     * @return
     *     possible object is
     *     {@link TelephonyServiceType }
     *     
     */
    public TelephonyServiceType getServiceType() {
        return serviceType;
    }

    /**
     * Sets the value of the serviceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TelephonyServiceType }
     *     
     */
    public void setServiceType(TelephonyServiceType value) {
        this.serviceType = value;
    }

    /**
     * Gets the value of the installationAddress property.
     * 
     * @return
     *     possible object is
     *     {@link AddressInformation }
     *     
     */
    public AddressInformation getInstallationAddress() {
        return installationAddress;
    }

    /**
     * Sets the value of the installationAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressInformation }
     *     
     */
    public void setInstallationAddress(AddressInformation value) {
        this.installationAddress = value;
    }

    /**
     * Gets the value of the connectionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConnectionDate() {
        return connectionDate;
    }

    /**
     * Sets the value of the connectionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConnectionDate(String value) {
        this.connectionDate = value;
    }

    /**
     * Gets the value of the imsi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getIMSI() {
        return imsi;
    }

    /**
     * Sets the value of the imsi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIMSI(byte[] value) {
        this.imsi = ((byte[]) value);
    }

    //Fix for TP04
    public byte[] getImsi() {
        return imsi;
    }

    public void setImsi(byte[] value) {
        this.imsi = ((byte[]) value);
    }
    
    /**
     * Gets the value of the carrierPreselect property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCarrierPreselect() {
        return carrierPreselect;
    }

    /**
     * Sets the value of the carrierPreselect property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCarrierPreselect(Boolean value) {
        this.carrierPreselect = value;
    }

    /**
     * Gets the value of the lineStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineStatus() {
        return lineStatus;
    }

    /**
     * Sets the value of the lineStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineStatus(String value) {
        this.lineStatus = value;
    }

    /**
     * Gets the value of the allocatedDeviceIDs property.
     * 
     * @return
     *     possible object is
     *     {@link AllocatedDeviceIDs }
     *     
     */
    public AllocatedDeviceIDs getAllocatedDeviceIDs() {
        return allocatedDeviceIDs;
    }

    /**
     * Sets the value of the allocatedDeviceIDs property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllocatedDeviceIDs }
     *     
     */
    public void setAllocatedDeviceIDs(AllocatedDeviceIDs value) {
        this.allocatedDeviceIDs = value;
    }

    /**
     * Gets the value of the pukCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPUKCode() {
        return pukCode;
    }

    /**
     * Sets the value of the pukCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPUKCode(String value) {
        this.pukCode = value;
    }

    /**
     * Gets the value of the puk2Code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPUK2Code() {
        return puk2Code;
    }

    /**
     * Sets the value of the puk2Code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPUK2Code(String value) {
        this.puk2Code = value;
    }

    /**
     * Gets the value of the imei property.
     * 
     * @return
     *     possible object is
     *     {@link IMEI }
     *     
     */
    public IMEI getIMEI() {
        return imei;
    }

    /**
     * Sets the value of the imei property.
     * 
     * @param value
     *     allowed object is
     *     {@link IMEI }
     *     
     */
    public void setIMEI(IMEI value) {
        this.imei = value;
    }

    /**
     * Gets the value of the nationalTelephonySubscriptionInfo property.
     * 
     * @return
     *     possible object is
     *     {@link NationalTelephonySubscriptionInfo }
     *     
     */
    public NationalTelephonySubscriptionInfo getNationalTelephonySubscriptionInfo() {
        return nationalTelephonySubscriptionInfo;
    }

    /**
     * Sets the value of the nationalTelephonySubscriptionInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link NationalTelephonySubscriptionInfo }
     *     
     */
    public void setNationalTelephonySubscriptionInfo(NationalTelephonySubscriptionInfo value) {
        this.nationalTelephonySubscriptionInfo = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="PartyNumber" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}PartyNumber"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "partyNumber"
    })
    public static class RegisteredNumbers {

        @XmlElement(name = "PartyNumber")
        protected List<String> partyNumber;

        /**
         * Gets the value of the partyNumber property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the partyNumber property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPartyNumber().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getPartyNumber() {
            if (partyNumber == null) {
                partyNumber = new ArrayList<String>();
            }
            return this.partyNumber;
        }

    }

}
