//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.14 at 10:55:58 AM BST 
//


package org.etsi.uri._02657.v1_1_1_.retaineddata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TelephonyServiceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TelephonyServiceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="private" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *         &lt;element name="privatePABX" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *         &lt;element name="publicPayphone" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TelephonyServiceType", propOrder = {
    "_private",
    "privatePABX",
    "publicPayphone"
})
public class TelephonyServiceType {

    @XmlElement(name = "private")
    protected NULL _private;
    protected NULL privatePABX;
    protected NULL publicPayphone;

    /**
     * Gets the value of the private property.
     * 
     * @return
     *     possible object is
     *     {@link NULL }
     *     
     */
    public NULL getPrivate() {
        return _private;
    }

    /**
     * Sets the value of the private property.
     * 
     * @param value
     *     allowed object is
     *     {@link NULL }
     *     
     */
    public void setPrivate(NULL value) {
        this._private = value;
    }

    /**
     * Gets the value of the privatePABX property.
     * 
     * @return
     *     possible object is
     *     {@link NULL }
     *     
     */
    public NULL getPrivatePABX() {
        return privatePABX;
    }

    /**
     * Sets the value of the privatePABX property.
     * 
     * @param value
     *     allowed object is
     *     {@link NULL }
     *     
     */
    public void setPrivatePABX(NULL value) {
        this.privatePABX = value;
    }

    /**
     * Gets the value of the publicPayphone property.
     * 
     * @return
     *     possible object is
     *     {@link NULL }
     *     
     */
    public NULL getPublicPayphone() {
        return publicPayphone;
    }

    /**
     * Sets the value of the publicPayphone property.
     * 
     * @param value
     *     allowed object is
     *     {@link NULL }
     *     
     */
    public void setPublicPayphone(NULL value) {
        this.publicPayphone = value;
    }

}
