//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.14 at 10:55:58 AM BST 
//


package org.etsi.uri._02657.v1_1_1_.retaineddata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TelephonyRecord complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TelephonyRecord">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="telephonySubscriber" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}TelephonySubscriber"/>
 *         &lt;element name="telephonyBillingDetails" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}TelephonyBillingDetails"/>
 *         &lt;element name="telephonyServiceUsage" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}TelephonyServiceUsage"/>
 *         &lt;element name="telephonyDevice" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}TelephonyDevice"/>
 *         &lt;element name="telephonyNetworkElement" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}TelephonyNetworkElement"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TelephonyRecord", propOrder = {
    "telephonySubscriber",
    "telephonyBillingDetails",
    "telephonyServiceUsage",
    "telephonyDevice",
    "telephonyNetworkElement"
})
public class TelephonyRecord {

    protected TelephonySubscriber telephonySubscriber;
    protected TelephonyBillingDetails telephonyBillingDetails;
    protected TelephonyServiceUsage telephonyServiceUsage;
    protected TelephonyDevice telephonyDevice;
    protected TelephonyNetworkElement telephonyNetworkElement;

    /**
     * Gets the value of the telephonySubscriber property.
     * 
     * @return
     *     possible object is
     *     {@link TelephonySubscriber }
     *     
     */
    public TelephonySubscriber getTelephonySubscriber() {
        return telephonySubscriber;
    }

    /**
     * Sets the value of the telephonySubscriber property.
     * 
     * @param value
     *     allowed object is
     *     {@link TelephonySubscriber }
     *     
     */
    public void setTelephonySubscriber(TelephonySubscriber value) {
        this.telephonySubscriber = value;
    }

    /**
     * Gets the value of the telephonyBillingDetails property.
     * 
     * @return
     *     possible object is
     *     {@link TelephonyBillingDetails }
     *     
     */
    public TelephonyBillingDetails getTelephonyBillingDetails() {
        return telephonyBillingDetails;
    }

    /**
     * Sets the value of the telephonyBillingDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link TelephonyBillingDetails }
     *     
     */
    public void setTelephonyBillingDetails(TelephonyBillingDetails value) {
        this.telephonyBillingDetails = value;
    }

    /**
     * Gets the value of the telephonyServiceUsage property.
     * 
     * @return
     *     possible object is
     *     {@link TelephonyServiceUsage }
     *     
     */
    public TelephonyServiceUsage getTelephonyServiceUsage() {
        return telephonyServiceUsage;
    }

    /**
     * Sets the value of the telephonyServiceUsage property.
     * 
     * @param value
     *     allowed object is
     *     {@link TelephonyServiceUsage }
     *     
     */
    public void setTelephonyServiceUsage(TelephonyServiceUsage value) {
        this.telephonyServiceUsage = value;
    }

    /**
     * Gets the value of the telephonyDevice property.
     * 
     * @return
     *     possible object is
     *     {@link TelephonyDevice }
     *     
     */
    public TelephonyDevice getTelephonyDevice() {
        return telephonyDevice;
    }

    /**
     * Sets the value of the telephonyDevice property.
     * 
     * @param value
     *     allowed object is
     *     {@link TelephonyDevice }
     *     
     */
    public void setTelephonyDevice(TelephonyDevice value) {
        this.telephonyDevice = value;
    }

    /**
     * Gets the value of the telephonyNetworkElement property.
     * 
     * @return
     *     possible object is
     *     {@link TelephonyNetworkElement }
     *     
     */
    public TelephonyNetworkElement getTelephonyNetworkElement() {
        return telephonyNetworkElement;
    }

    /**
     * Sets the value of the telephonyNetworkElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TelephonyNetworkElement }
     *     
     */
    public void setTelephonyNetworkElement(TelephonyNetworkElement value) {
        this.telephonyNetworkElement = value;
    }

}
