//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.14 at 10:55:58 AM BST 
//


package org.etsi.uri._02657.v1_1_1_.retaineddata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import org.etsi.uri._02657.v1_3_1_1.retaineddata.NationalTelephonyNetworkElement;
import org.etsi.uri._02657.v1_7_1_.retaineddata.TransmitterDetails;


/**
 * <p>Java class for TelephonyNetworkElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TelephonyNetworkElement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="telephonyNetworkID" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}TelephonyNetworkID" minOccurs="0"/>
 *         &lt;element name="cellInformation" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}Location" minOccurs="0"/>
 *         &lt;element name="validity" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}TimeSpan" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/02657/v1.3.1#1/RetainedData}nationalTelephonyNetworkElement" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/02657/v1.7.1#/RetainedData}transmitterDetails" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TelephonyNetworkElement", propOrder = {
    "telephonyNetworkID",
    "cellInformation",
    "validity",
    "nationalTelephonyNetworkElement",
    "transmitterDetails"
})
public class TelephonyNetworkElement {

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] telephonyNetworkID;
    protected Location cellInformation;
    protected TimeSpan validity;
    @XmlElement(namespace = "http://uri.etsi.org/02657/v1.3.1#1/RetainedData")
    protected NationalTelephonyNetworkElement nationalTelephonyNetworkElement;
    @XmlElement(namespace = "http://uri.etsi.org/02657/v1.7.1#/RetainedData")
    protected TransmitterDetails transmitterDetails;

    /**
     * Gets the value of the telephonyNetworkID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getTelephonyNetworkID() {
        return telephonyNetworkID;
    }

    /**
     * Sets the value of the telephonyNetworkID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelephonyNetworkID(byte[] value) {
        this.telephonyNetworkID = ((byte[]) value);
    }

    /**
     * Gets the value of the cellInformation property.
     * 
     * @return
     *     possible object is
     *     {@link Location }
     *     
     */
    public Location getCellInformation() {
        return cellInformation;
    }

    /**
     * Sets the value of the cellInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Location }
     *     
     */
    public void setCellInformation(Location value) {
        this.cellInformation = value;
    }

    /**
     * Gets the value of the validity property.
     * 
     * @return
     *     possible object is
     *     {@link TimeSpan }
     *     
     */
    public TimeSpan getValidity() {
        return validity;
    }

    /**
     * Sets the value of the validity property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeSpan }
     *     
     */
    public void setValidity(TimeSpan value) {
        this.validity = value;
    }

    /**
     * Gets the value of the nationalTelephonyNetworkElement property.
     * 
     * @return
     *     possible object is
     *     {@link NationalTelephonyNetworkElement }
     *     
     */
    public NationalTelephonyNetworkElement getNationalTelephonyNetworkElement() {
        return nationalTelephonyNetworkElement;
    }

    /**
     * Sets the value of the nationalTelephonyNetworkElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link NationalTelephonyNetworkElement }
     *     
     */
    public void setNationalTelephonyNetworkElement(NationalTelephonyNetworkElement value) {
        this.nationalTelephonyNetworkElement = value;
    }

    /**
     * Gets the value of the transmitterDetails property.
     * 
     * @return
     *     possible object is
     *     {@link TransmitterDetails }
     *     
     */
    public TransmitterDetails getTransmitterDetails() {
        return transmitterDetails;
    }

    /**
     * Sets the value of the transmitterDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransmitterDetails }
     *     
     */
    public void setTransmitterDetails(TransmitterDetails value) {
        this.transmitterDetails = value;
    }

}
