//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.14 at 10:55:58 AM BST 
//


package org.etsi.uri._02657.v1_1_1_.retaineddata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UMTSLocation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UMTSLocation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="point" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}GA_Point"/>
 *         &lt;element name="pointWithUnCertainty" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}GA_PointWithUnCertainty"/>
 *         &lt;element name="polygon" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}GA_Polygon"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UMTSLocation", propOrder = {
    "point",
    "pointWithUnCertainty",
    "polygon"
})
public class UMTSLocation {

    protected GAPoint point;
    protected GAPointWithUnCertainty pointWithUnCertainty;
    protected GAPolygon polygon;

    /**
     * Gets the value of the point property.
     * 
     * @return
     *     possible object is
     *     {@link GAPoint }
     *     
     */
    public GAPoint getPoint() {
        return point;
    }

    /**
     * Sets the value of the point property.
     * 
     * @param value
     *     allowed object is
     *     {@link GAPoint }
     *     
     */
    public void setPoint(GAPoint value) {
        this.point = value;
    }

    /**
     * Gets the value of the pointWithUnCertainty property.
     * 
     * @return
     *     possible object is
     *     {@link GAPointWithUnCertainty }
     *     
     */
    public GAPointWithUnCertainty getPointWithUnCertainty() {
        return pointWithUnCertainty;
    }

    /**
     * Sets the value of the pointWithUnCertainty property.
     * 
     * @param value
     *     allowed object is
     *     {@link GAPointWithUnCertainty }
     *     
     */
    public void setPointWithUnCertainty(GAPointWithUnCertainty value) {
        this.pointWithUnCertainty = value;
    }

    /**
     * Gets the value of the polygon property.
     * 
     * @return
     *     possible object is
     *     {@link GAPolygon }
     *     
     */
    public GAPolygon getPolygon() {
        return polygon;
    }

    /**
     * Sets the value of the polygon property.
     * 
     * @param value
     *     allowed object is
     *     {@link GAPolygon }
     *     
     */
    public void setPolygon(GAPolygon value) {
        this.polygon = value;
    }

}
