//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.14 at 10:55:58 AM BST 
//


package org.etsi.uri._02657.v1_3_1_1.retaineddata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CSPReferralInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CSPReferralInformation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cSPID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="referralField" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="referralValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="furtherDetails" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CSPReferralInformation", propOrder = {
    "cspid",
    "referralField",
    "referralValue",
    "furtherDetails"
})
public class CSPReferralInformation {

    @XmlElement(name = "cSPID")
    protected String cspid;
    protected String referralField;
    protected String referralValue;
    protected String furtherDetails;

    /**
     * Gets the value of the cspid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCSPID() {
        return cspid;
    }

    /**
     * Sets the value of the cspid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCSPID(String value) {
        this.cspid = value;
    }

    /**
     * Gets the value of the referralField property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferralField() {
        return referralField;
    }

    /**
     * Sets the value of the referralField property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferralField(String value) {
        this.referralField = value;
    }

    /**
     * Gets the value of the referralValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferralValue() {
        return referralValue;
    }

    /**
     * Sets the value of the referralValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferralValue(String value) {
        this.referralValue = value;
    }

    /**
     * Gets the value of the furtherDetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFurtherDetails() {
        return furtherDetails;
    }

    /**
     * Sets the value of the furtherDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFurtherDetails(String value) {
        this.furtherDetails = value;
    }

}
