//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.14 at 10:55:58 AM BST 
//


package org.etsi.uri._02657.v1_3_1_1.retaineddata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import org.etsi.uri._02657.v1_1_1_.retaineddata.NULL;


/**
 * <p>Java class for GPRSEvent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GPRSEvent">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="pDPContextActivation" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *         &lt;element name="pDPContextDeactivation" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *         &lt;element name="gPRSAttach" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *         &lt;element name="gPRSDetach" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *         &lt;element name="locationInfoUpdate" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *         &lt;element name="pDPContextModification" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *         &lt;element name="servingSystem" type="{http://uri.etsi.org/02657/v1.1.1#/RetainedData}NULL"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GPRSEvent", propOrder = {
    "pdpContextActivation",
    "pdpContextDeactivation",
    "gprsAttach",
    "gprsDetach",
    "locationInfoUpdate",
    "pdpContextModification",
    "servingSystem"
})
public class GPRSEvent {

    @XmlElement(name = "pDPContextActivation")
    protected NULL pdpContextActivation;
    @XmlElement(name = "pDPContextDeactivation")
    protected NULL pdpContextDeactivation;
    @XmlElement(name = "gPRSAttach")
    protected NULL gprsAttach;
    @XmlElement(name = "gPRSDetach")
    protected NULL gprsDetach;
    protected NULL locationInfoUpdate;
    @XmlElement(name = "pDPContextModification")
    protected NULL pdpContextModification;
    protected NULL servingSystem;

    /**
     * Gets the value of the pdpContextActivation property.
     * 
     * @return
     *     possible object is
     *     {@link NULL }
     *     
     */
    public NULL getPDPContextActivation() {
        return pdpContextActivation;
    }

    /**
     * Sets the value of the pdpContextActivation property.
     * 
     * @param value
     *     allowed object is
     *     {@link NULL }
     *     
     */
    public void setPDPContextActivation(NULL value) {
        this.pdpContextActivation = value;
    }

    /**
     * Gets the value of the pdpContextDeactivation property.
     * 
     * @return
     *     possible object is
     *     {@link NULL }
     *     
     */
    public NULL getPDPContextDeactivation() {
        return pdpContextDeactivation;
    }

    /**
     * Sets the value of the pdpContextDeactivation property.
     * 
     * @param value
     *     allowed object is
     *     {@link NULL }
     *     
     */
    public void setPDPContextDeactivation(NULL value) {
        this.pdpContextDeactivation = value;
    }

    /**
     * Gets the value of the gprsAttach property.
     * 
     * @return
     *     possible object is
     *     {@link NULL }
     *     
     */
    public NULL getGPRSAttach() {
        return gprsAttach;
    }

    /**
     * Sets the value of the gprsAttach property.
     * 
     * @param value
     *     allowed object is
     *     {@link NULL }
     *     
     */
    public void setGPRSAttach(NULL value) {
        this.gprsAttach = value;
    }

    /**
     * Gets the value of the gprsDetach property.
     * 
     * @return
     *     possible object is
     *     {@link NULL }
     *     
     */
    public NULL getGPRSDetach() {
        return gprsDetach;
    }

    /**
     * Sets the value of the gprsDetach property.
     * 
     * @param value
     *     allowed object is
     *     {@link NULL }
     *     
     */
    public void setGPRSDetach(NULL value) {
        this.gprsDetach = value;
    }

    /**
     * Gets the value of the locationInfoUpdate property.
     * 
     * @return
     *     possible object is
     *     {@link NULL }
     *     
     */
    public NULL getLocationInfoUpdate() {
        return locationInfoUpdate;
    }

    /**
     * Sets the value of the locationInfoUpdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link NULL }
     *     
     */
    public void setLocationInfoUpdate(NULL value) {
        this.locationInfoUpdate = value;
    }

    /**
     * Gets the value of the pdpContextModification property.
     * 
     * @return
     *     possible object is
     *     {@link NULL }
     *     
     */
    public NULL getPDPContextModification() {
        return pdpContextModification;
    }

    /**
     * Sets the value of the pdpContextModification property.
     * 
     * @param value
     *     allowed object is
     *     {@link NULL }
     *     
     */
    public void setPDPContextModification(NULL value) {
        this.pdpContextModification = value;
    }

    /**
     * Gets the value of the servingSystem property.
     * 
     * @return
     *     possible object is
     *     {@link NULL }
     *     
     */
    public NULL getServingSystem() {
        return servingSystem;
    }

    /**
     * Sets the value of the servingSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link NULL }
     *     
     */
    public void setServingSystem(NULL value) {
        this.servingSystem = value;
    }

}
