//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.14 at 10:55:58 AM BST 
//


package org.etsi.uri._02657.v1_3_1_1.retaineddata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import org.etsi.uri._02657.v1_7_1_.retaineddata.SubscriptionCreationInformation;


/**
 * <p>Java class for NationalTelephonySubscriptionInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NationalTelephonySubscriptionInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="countryCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{http://uri.etsi.org/02657/v1.7.1#/RetainedData}subscriptionCreationInformation" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NationalTelephonySubscriptionInfo", propOrder = {
    "countryCode",
    "subscriptionCreationInformation"
})
public class NationalTelephonySubscriptionInfo {

    @XmlElement(required = true)
    protected String countryCode;
    @XmlElement(namespace = "http://uri.etsi.org/02657/v1.7.1#/RetainedData")
    protected SubscriptionCreationInformation subscriptionCreationInformation;

    /**
     * Gets the value of the countryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * Sets the value of the countryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryCode(String value) {
        this.countryCode = value;
    }

    /**
     * Gets the value of the subscriptionCreationInformation property.
     * 
     * @return
     *     possible object is
     *     {@link SubscriptionCreationInformation }
     *     
     */
    public SubscriptionCreationInformation getSubscriptionCreationInformation() {
        return subscriptionCreationInformation;
    }

    /**
     * Sets the value of the subscriptionCreationInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubscriptionCreationInformation }
     *     
     */
    public void setSubscriptionCreationInformation(SubscriptionCreationInformation value) {
        this.subscriptionCreationInformation = value;
    }

}
