//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.14 at 10:55:58 AM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://uri.etsi.org/02657/v1.3.1#1/RetainedData", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.etsi.uri._02657.v1_3_1_1.retaineddata;
