
package com.ctg.dms.customerprofile;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-hudson-48-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "MIDUSCustomerProfile", targetNamespace = "http://www.three.co.uk/midus/bw/wsdl/midusservice", wsdlLocation = "file:/C:/workspace/Midus-HEAD/Midus/etc/IDUGetCustomerProfile.wsdl")
public class MIDUSCustomerProfile
    extends Service
{

    private final static URL MIDUSCUSTOMERPROFILE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.ctg.dms.customerprofile.MIDUSCustomerProfile.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.ctg.dms.customerprofile.MIDUSCustomerProfile.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/workspace/Midus-HEAD/Midus/etc/IDUGetCustomerProfile.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/workspace/Midus-HEAD/Midus/etc/IDUGetCustomerProfile.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MIDUSCUSTOMERPROFILE_WSDL_LOCATION = url;
    }

    public MIDUSCustomerProfile(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MIDUSCustomerProfile() {
        super(MIDUSCUSTOMERPROFILE_WSDL_LOCATION, new QName("http://www.three.co.uk/midus/bw/wsdl/midusservice", "MIDUSCustomerProfile"));
    }

    /**
     * 
     * @return
     *     returns MIDUSCustomer
     */
    @WebEndpoint(name = "MIDUSCustomer")
    public MIDUSCustomer getMIDUSCustomer() {
        return super.getPort(new QName("http://www.three.co.uk/midus/bw/wsdl/midusservice", "MIDUSCustomer"), MIDUSCustomer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MIDUSCustomer
     */
    @WebEndpoint(name = "MIDUSCustomer")
    public MIDUSCustomer getMIDUSCustomer(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.three.co.uk/midus/bw/wsdl/midusservice", "MIDUSCustomer"), MIDUSCustomer.class, features);
    }

}
